---
title: "transcripts-exp4"
format: html
execute:
  echo: false
  eval: false
---

Test tokenization

```{r}
tar_load(starts_with("df"))
tar_load(matches("^tokens_"))
df_raw           <- open_dataset(df_raw)
df_clean         <- open_dataset(df_clean)
tokens_raw       <- open_dataset(tokens_raw)
tokens_clean     <- open_dataset(tokens_clean)
tokens_bi_raw    <- open_dataset(tokens_bi_raw)
tokens_bi_clean  <- open_dataset(tokens_bi_clean)
tokens_tri_raw   <- open_dataset(tokens_tri_raw)
tokens_tri_clean <- open_dataset(tokens_tri_clean)
```

```{r}
list_df_tokens <- list(
  "df_raw" = df_raw,
  "df_clean" = df_clean,
  "tokens_raw" = tokens_raw,
  "tokens_clean" = tokens_clean,
  "tokens_bi_raw" = tokens_bi_raw,
  "tokens_bi_clean" = tokens_bi_clean
)

list_df_tokens |> map(\(x) dim(x))
```

```{r}

```

# raw

```{r}

tokens_raw |> 
  select(season:sp4) |>
  filter(type == "dialogue") |> 
  filter(when_any(
    when_all(
      sp3 %in% characters$first_name,
      sp4 %in% characters$last_name
    ),
    when_all(
      is.na(sp3),
      sp4 %in% characters$last_name
    )
  )) |> 
  collect() |> 
  count(sp3, sp4) |> 
  arrange(sp4, sp3)

tokens_raw |> 
  select(season:sp4) |>
  filter(type == "dialogue") |> 
  filter(when_any(
    when_all(
      sp3 %in% characters$first_name,
      sp4 %in% characters$last_name
    ),
    when_all(
      is.na(sp3),
      sp4 %in% characters$last_name
    )
  )) |> 
  collect() |> 
  count(sp3, sp4) |> 
  arrange(sp4, sp3) |> 
  count(sp4)

```

## Count words spoken

```{r}
tokens_raw |> 
  select(season:sp4) |>
  filter(type == "dialogue") |> 
  filter(when_any(
    when_all(
      sp3 %in% characters$first_name,
      sp4 %in% characters$last_name
    ),
    when_all(
      is.na(sp3),
      sp4 %in% characters$last_name
    )
  )) |> 
  collect() |> 
  filter(when_all(
    when_any(
      sp3 %in% characters[characters$type == "main", ]$first_name,
      is.na(sp3)
    ),
    sp4 %in% characters[characters$type == "main", ]$last_name
  )) |> 
  count(sp4) |> 
  arrange(desc(n))

# for recurring characters, some are referred to by only last name and some are referred to by both first and last name
# I can't count is.na(sp3) and sp4 == "BRADFORD" because those are Tim's lines, not Isabel's

tokens_raw |> 
  select(season:sp4) |>
  filter(type == "dialogue") |> 
  filter(when_any(
    when_all(
      sp3 %in% characters$first_name,
      sp4 %in% characters$last_name
    ),
    when_all(
      is.na(sp3),
      sp4 %in% characters$last_name
    )
  )) |> 
  collect() |> 
  filter(when_all(
    sp3 %in% characters[characters$type == "recurring", ]$first_name,
    sp4 %in% characters[characters$type == "recurring", ]$last_name
  )) |> 
  count(sp3, sp4) |> 
  arrange(desc(n))
```

```{r}

tokens_raw |> 
  select(season:sp4) |>
  filter(type == "dialogue") |> 
  filter(when_any(
    when_all(
      sp3 %in% characters$first_name,
      sp4 %in% characters$last_name
    ),
    when_all(
      is.na(sp3),
      sp4 %in% characters$last_name
    )
  )) |> 
  dim()

tokens_raw |> 
  select(season:sp4) |>
  filter(type == "dialogue") |> 
  filter_characters("all") |> 
  dim()

```

```{r}
tokens_raw |> 
  select(season:sp4) |>
  filter(type == "dialogue") |> 
  filter_characters("top6") |> 
  count(sp4, sort = TRUE) |> 
  collect()

tokens_raw |> 
  select(season:sp4) |>
  filter(type == "dialogue") |> 
  filter_characters("main") |> 
  count(sp4, sort = TRUE) |> 
  collect()
```

```{r}
tokens_raw |> 
  select(season:sp4) |> 
  filter(type == "dialogue") |> 
  count(word, sort = TRUE) |> 
  collect()
```


## Season appearances by type

```{r}
character_status |> 
  # filter(type == "main") |> 
  group_by(character_first, character_last) |> 
  count(status) |> 
  filter_out(is.na(status)) |> 
  pivot_wider(names_from = status, values_from = n) |> 
  relocate(c(main, recurring, guest), .after = character_last) |> 
  arrange(desc(main), desc(recurring), desc(guest), character_last) |> 
  mutate(total = sum(main, recurring, guest, na.rm = TRUE))
```

## Filter out stop words

```{r}
tokens_raw |> 
  select(season:sp4) |>
  filter(type == "dialogue") |> 
  filter(when_any(
    when_all(
      sp3 %in% characters$first_name,
      sp4 %in% characters$last_name
    ),
    when_all(
      is.na(sp3),
      sp4 %in% characters$last_name
    )
  )) |> 
  anti_join(stop_words) |> 
  collect() |> 
  filter(when_all(
    when_any(
      sp3 %in% characters[characters$type == "main", ]$first_name,
      is.na(sp3)
    ),
    sp4 %in% characters[characters$type == "main", ]$last_name
  )) |> 
  count(sp4) |> 
  arrange(desc(n))
```

```{r}
total_words <- tokens_raw |> 
  filter(type == "dialogue") |> 
  group_by(season, episode) |> 
  summarise(total_words = n()) |> 
  collect()

tokens_raw |> 
  select(season:sp4) |> 
  filter(type == "dialogue") |> 
  count(season, episode, word, sort = TRUE) |> 
  collect() |> 
  # anti_join(stop_words |> filter(lexicon == "SMART"), join_by(word)) |> 
  left_join(total_words, join_by(season, episode)) |> 
  mutate(frequency = n/total_words) |> 
  filter(word == "yeah")
```

```{r}
tokens_raw |> 
  select(ep_number, season:sp4) |> 
  filter(type == "dialogue") |> 
  count(ep_number, word, sort = TRUE) |> 
  collect() |> 
  bind_tf_idf(word, ep_number, n) |> 
  anti_join(stop_words |> filter(lexicon == "SMART"), join_by(word))
```

```{r}
tokens_raw |> 
  select(ep_number, season:sp4) |> 
  filter(type == "dialogue") |> 
  count(ep_number, word, sort = TRUE) |> 
  collect() |> 
  bind_tf_idf(word, ep_number, n) |> 
  anti_join(stop_words |> filter(lexicon == "SMART"), join_by(word)) |> 
  arrange(desc(idf))
```

```{r}
tokens_raw |> 
  select(ep_number, season:sp4) |> 
  filter(type == "dialogue") |> 
  count(ep_number, word, sort = TRUE) |> 
  collect() |> 
  bind_tf_idf(word, ep_number, n) |> 
  anti_join(stop_words |> filter(lexicon == "SMART"), join_by(word)) |> 
  arrange(desc(tf_idf))
```

histograms for tf, idf, tf-idf

```{r}
tokens_raw |> 
  select(ep_number, season:sp4) |> 
  filter(type == "dialogue") |> 
  count(ep_number, word, sort = TRUE) |> 
  collect() |> 
  bind_tf_idf(word, ep_number, n) |> 
  anti_join(stop_words |> filter(lexicon == "SMART"), join_by(word)) |> 
  arrange(desc(tf_idf)) |> 
  ggplot() +
  geom_histogram(aes(tf), fill = teal, bins = 60) +
  theme_light()

tokens_raw |> 
  select(ep_number, season:sp4) |> 
  filter(type == "dialogue") |> 
  count(ep_number, word, sort = TRUE) |> 
  collect() |> 
  bind_tf_idf(word, ep_number, n) |> 
  anti_join(stop_words |> filter(lexicon == "SMART"), join_by(word)) |> 
  arrange(desc(tf_idf)) |> 
  ggplot() +
  geom_histogram(aes(idf), fill = teal, bins = 60) +
  theme_light()

tokens_raw |> 
  select(ep_number, season:sp4) |> 
  filter(type == "dialogue") |> 
  count(ep_number, word, sort = TRUE) |> 
  collect() |> 
  bind_tf_idf(word, ep_number, n) |> 
  anti_join(stop_words |> filter(lexicon == "SMART"), join_by(word)) |> 
  arrange(desc(tf_idf)) |> 
  ggplot() +
  geom_histogram(aes(tf_idf), fill = teal, bins = 60) +
  theme_light()
```

```{r}
tokens_raw |> 
  select(ep_number, season:sp4) |> 
  filter(type == "dialogue") |> 
  count(ep_number, word, sort = TRUE) |> 
  collect() |> 
  bind_tf_idf(word, ep_number, n) |> 
  anti_join(stop_words |> filter(lexicon == "SMART"), join_by(word)) |> 
  left_join(
    transcripts |> select(ep_number, season:title) |> collect(),
    join_by(ep_number)
  ) |> 
  select(-ep_number) |> 
  relocate(season:title) |> 
  filter(season == 1, episode <= 4) |> 
  slice_max(tf_idf, n = 15, by = c(season, episode)) |> 
  ggplot(aes(word |> fct_reorder(tf_idf), tf_idf)) + 
  geom_col() +
  facet_wrap(~interaction(season, episode), scales = "free") + 
  coord_flip()
```


## bi

```{r}

tokens_bi_raw |> 
  relocate(c(unnested, word), .after = speaker_note) |> 
  select(season:word) |> 
  head(300) |> 
  collect() |> 
  separate_wider_delim(word, " ", names = c("word1", "word2"))

```

## tri

```{r}
tokens_tri_raw |> 
  select(season:word3) |>
  head(n=300) |> 
  collect()
```

# clean
