---
title: "transcripts-exp2"
format: html
execute:
  eval: false
---

```{r}
tar_load(transcripts)
tar_load(transcripts_html)
tar_load(transcripts_lines)
tar_load(transcripts_clean)
transcripts_lines <- open_dataset(transcripts_lines, format = "parquet")
transcripts_clean <- open_dataset(transcripts_clean, format = "parquet")
```

```{r}
#| label: test-base

test_base <- transcripts |> 
  pre_clean() |> 
  clean_speaker_names() |>
  remove_translations() |> 
  add_brackets() |>
  replace_italics() |> 
  add_space() |> 
  # clean_proper_nouns() |>  # instead of using _ to join words, check ngrams?
  split_transcripts() |>
  shift_italics_tags() |>
  clean_previously() |> 
  clean_scene_headings() |> 
  clean_captions() |> 
  clean_other() |> 
  pre_clean_lyrics()

test_base2 <- test_base |> 
  assign_speaker_names() |> 
  extract_speaker_note() |> 
  insert_sentinels() |> 
  unitalicize_descriptions() |> 
  unify_sentinels() |> 
  separate_at_sentinels()

```

```{r}
#| label: test-objects

test <- test_base |> 
  arrow_table()

test2 <- test_base |> 
  assign_speaker_names() |> 
  extract_speaker_note() |> 
  arrow_table()

test3 <- test_base |> 
  assign_speaker_names() |> 
  insert_sentinels() |> 
  extract_speaker_note() |> 
  arrow_table()

test3a <- test_base |> 
  assign_speaker_names() |> 
  insert_sentinels() |> 
  unify_sentinels() |> 
  extract_speaker_note() |> 
  arrow_table()

test4 <- test_base |> 
  assign_speaker_names() |> 
  extract_speaker_note() |> 
  insert_sentinels() |> 
  unify_sentinels() |> 
  separate_at_sentinels() |> 
  arrow_table()

test4a <- test_base |> 
  assign_speaker_names() |> 
  extract_speaker_note() |> 
  insert_sentinels() |> 
  unitalicize_descriptions() |> 
  arrow_table()

test4b <- test_base |> 
  assign_speaker_names() |> 
  extract_speaker_note() |> 
  insert_sentinels() |> 
  unitalicize_descriptions() |> 
  unify_sentinels() |> 
  arrow_table()

test5 <- test_base2 |> 
  arrow_table()

test6 <- test_base2 |> 
  reclassify_type() |> 
  fill_speaker_info() |> 
  arrow_table()

test7 <- test_base2 |>
  reclassify_type() |>
  fill_speaker_info() |>
  clean_multispeaker_names() |>
  arrow_table()

```

# test

```{r}
test |> 
  select(season, episode, type, transcript) |>
  # select(season, episode, type, speaker, transcript) |>
  # select(season, episode, type, speaker, speaker_note, transcript) |>
  # filter(season == 3) |>
  filter(season == 3, episode == 1) |>
  collect() |> 
  # assign_speaker_names() |>
  # insert_sentinels() |>
  # separate_at_sentinels() |> 
  # extract_speaker_note() |>
  # filter_out(is.na(speaker_note)) |> 
  # filter(str_detect(transcript, "^(\\(|\\[)")) |> gt()
  # count(type)
  peek_rows(transcript, "Birds singing", fmt = "g")
  # peek_rows(transcript, "^<i>.+</i>.+", fmt = "g")
  # peek_rows(transcript, ".+<i>.+</i>.*", fmt = "g")

```

# test2

```{r}
test2 |> 
  select(season, episode, type, speaker, speaker_note, transcript) |>
  collect() |> 
  peek_rows(transcript, "^<i>.+</i>.+", fmt = "g")

test2 |> 
  select(season, episode, type, speaker, speaker_note, transcript) |> 
  collect() |> 
  peek_rows(transcript, ".+<i>.+</i>.*", fmt = "g")
```

```{r}
test2 |> 
  select(season, episode, type, speaker, speaker_note, transcript) |> 
  collect() |> 
  peek_rows(transcript, "\u266a", fmt = "g")
```

```{r}
test2 |> 
  select(season:transcript) |> 
  # filter(is.na(type)) |> 
  filter(type == "scene_heading") |> 
  filter(str_detect(transcript, "<i>")) |> 
  collect() |> 
  gt()
```

# test3

```{r}
test3 |> 
  select(season, episode, type, speaker, speaker_note, transcript) |> 
  # filter(season == 1) |> 
  collect() |> 
  peek_rows(transcript, "\u266a", fmt = "g")
```

```{r}

tibble(x = c(
  test3 |> 
    select(season, episode, type, speaker, speaker_note, transcript) |> 
    filter(str_detect(transcript, "\u266a")) |> 
    collect() |> 
    pull(transcript)
)) |> separate_longer_delim(x, brown_square)

```

```{r}
#| label: check-sentinels

test3 |> check_sentinel(red_circle)     |> gt()
test3 |> check_sentinel(brown_square)   |> gt()  # 2
test3 |> check_sentinel(brown_circle)   |> gt()
test3 |> check_sentinel(red_loop)       |> gt()  # 4
test3 |> check_sentinel(red_cross)      |> gt()
test3 |> check_sentinel(blue_square)    |> gt()  # 6
test3 |> check_sentinel(blue_circle)    |> gt()
test3 |> check_sentinel(purple_circle)  |> gt()  # 8
test3 |> check_sentinel(blue_diamond)   |> gt()
test3 |> check_sentinel(red_square)     |> gt()  # 10
test3 |> check_sentinel(orange_diamond) |> gt()

```

```{r}
#| label: check-missing-sentinels

# check places where sentinels might be missing

missing_sentinels_pattern <- paste(
  "\\s[\\(\\[]",   # space before ( or [
  "[\\)\\]]\\s",   # space after ) or ]
  "\\s<i>",        # space before <i>
  "</i>\\s",       # space after </i>
  sep = "|"
)

test3 |>
  select(season, episode, type, speaker, transcript) |>
  # filter(type == "italics") |> 
  filter(str_detect(transcript, missing_sentinels_pattern)) |>
  # filter_out(str_detect(transcript, "</i>|[\\]\\)]$")) |> 
  collect() |> 
  gt()
```

```{r}
test3 |> 
  select(season, episode, type, speaker, speaker_note, transcript) |> 
  filter(season == 2, episode == 15) |> 
  collect() |> 
  unitalicize_descriptions() |> 
  gt()
  
```

## test3a

```{r}
test3a |> 
  select(season, episode, type, speaker, speaker_note, transcript) |> 
  filter(season == 1, episode == 1) |>
  collect() |> 
  peek_rows(transcript, "<i>|\\(|\\[", fmt = "g")
```

# test4

```{r}

test4 |> 
  select(season, episode, type, speaker, speaker_note, transcript) |> 
  # filter(season == 1, episode == 17) |>
  # filter(type == "dialogue") |> 
  collect() |> 
  # reclassify_type() |>
  # peek_rows(transcript, "<i>|\\(|\\[", fmt = "g")
  peek_rows(transcript, condition = transcript == "")

```

```{r}
test4 |> 
  select(season, episode, type, speaker, speaker_note, transcript) |> 
  filter(season == 2, episode == 15) |> 
  # filter(type == "dialogue") |> 
  collect() |> 
  reclassify_type() |>
  peek_rows(transcript, condition = transcript == "", fmt = "t") |>
  mutate(
    speaker = if_else(
      when_all(
        type == "italics",
        lag(transcript) == ""
      ),
      lag(speaker),
      speaker
    ),
    speaker_note = if_else(
      when_all(
        type == "italics",
        lag(transcript) == ""
      ),
      lag(speaker_note),
      speaker_note
    ),
    type = if_else(
      when_all(
        type == "italics",
        lag(transcript) == ""
      ),
      "dialogue",
      type
    ),
    speaker = if_else(
      when_all(
        type == "description",
        lag(type) == "dialogue",
        lag(transcript) == ""
      ),
      lag(speaker),
      speaker
    ),
    speaker = if_else(
      when_all(
        type == "dialogue",
        is.na(speaker),
        lag(transcript, n = 2) == ""
      ),
      lag(speaker, n = 2),
      speaker
    ),
    speaker_note = if_else(
      when_all(
        type == "dialogue",
        is.na(speaker_note),
        lag(transcript, n = 2) == ""
      ),
      lag(speaker_note, n = 2),
      speaker_note
    )
  ) |>
  gt()
```

# test5

```{r}
test5 |> 
  select(season, episode, type, speaker, speaker_note, transcript) |> 
  # filter(season == 1, episode == 17) |> 
  collect() |> 
  # peek_rows(transcript, "<i>|\\(|\\[", fmt = "g")
  peek_rows(transcript, condition = transcript == "")
```

```{r}

blue_true <- function(tbl) {
  
  tbl |> 
    tab_style(
    style = list(cell_fill(color = "lightblue")),
    locations = cells_body(
      columns = italicized_dialogue,
      rows = italicized_dialogue == TRUE
    )
  ) |> 
  tab_style(
    style = list(cell_fill(color = "lightblue")),
    locations = cells_body(
      columns = description_dialogue,
      rows = description_dialogue == TRUE
    )
  )
  
}

test5 |> 
  select(season, episode, type, speaker, speaker_note, transcript) |> 
  # filter(season == 1, episode == 6) |>
  collect() |> 
  # peek_rows(transcript, "<i>|\\(|\\[", fmt = "g")
  # peek_rows(transcript, condition = transcript == "", fmt = "t") |> 
  fill_speaker_info() |> 
  # fill_speaker_info() |>
  # fill_speaker_info() |>
  # peek_rows(transcript, condition = transcript == "") |>
  # peek_rows(transcript, condition = description_dialogue == TRUE) |>
  # peek_rows(speaker, condition = is.na(speaker)) |> 
  peek_rows(transcript, "Things hard to get to", before = 10, after = 5) |>
  blue_true()

```

# test6

```{r}
test6 |> 
  # select(ep_ID, season, episode, type, scene_type, transcript) |> 
  select(season:transcript) |>
  # select(season:last_col()) |> 
  # filter(season == 2, episode == 10) |> 
  filter(type == "italics") |> 
  # filter(type != "description", type != "italics") |> 
  # filter(str_detect(speaker, "\\s(?i)and\\s")) |>
  collect() |>
  # gt()
  peek_rows(transcript, "^<i>.+</i>.+$")
  # peek_rows(transcript, condition = transcript == "")
  # peek_rows(italicized_dialogue, "TRUE", before = 0, after = 0)

```

```{r}
test6 |> 
  unitalicize_descriptions2() |> 
  select(season:transcript) |> 
  filter(type != "scene_heading", !is.na(scene_type)) |> 
  collect() |> gt()

test6 |> 
  unitalicize_descriptions2() |> 
  select(season:transcript) |> 
  filter(type == "scene_heading", str_detect(transcript, "<i>"))

```

```{r}

test6 |> 
  select(season, episode, speaker, speaker_note, transcript) |> 
  distinct(speaker) |> 
  collect()

```

# multispeaker speaker names

```{r}
#| label: check-ms-names

# check pattern for recognizing multi-speaker speaker names separated by "and"

c(
  ms_name = "BISHOP and LOPEZ",
  ms_name = "NA'VI and THORSEN",
  ms_name = "WESLEY and DEL MONTE",
  dialogue = "BOLOs are out for Abril, and the DEA and FBI are launching",
  dialogue = "We need you and ... house while FBI and SWAT mobilize",
  dialogue = "BP and O2 are falling.",
  description = "(to NOLAN and CHEN)",
  description = "[LOPEZ and WESLEY leave the room]",
  unmarked_description = "LOPEZ and WEST are cruising",
  italics = "<i>OFFICERS ANGELA LOPEZ and TALIA BISHOP are coming down...</i>"
  
) |> 
  str_detect("^[A-Z\']+\\sand\\s[A-Z]+\\s?[A-Z]+$")

# ^[A-Z\']+\sand\s[A-Z]+\s?[A-Z]+
```

```{r}

multispeaker_lines <- test6 |> 
  select(season, episode, line, type, dialogue_type, speaker, speaker_note, transcript) |>
  filter(type == "dialogue") |>
  # filter(str_detect(speaker, "[A-Z]{3,}\\sand\\s[A-Z]{3,}")) |> 
  filter(str_detect(speaker, ",|&|\\s(?i)and\\s|/")) |> 
  collect()

# multispeaker_lines |> 
#   mutate(
#     speaker = speaker |> 
#       replace_values(from = aliases$pattern, to = aliases$name),
#     speaker = speaker |> 
#       str_replace_all(",\\s", green_circle) |> 
#       str_replace_all("/", green_circle) |> 
#       str_replace_all("\\s?&\\s", green_circle) |> 
#       str_replace_all("\\s?(?i)and\\s", green_circle) |> 
#       str_remove_all("(?<=\U1f7e2)\U1f7e2")
#   )

multispeaker_lines |> gt()

multispeaker_lines |> 
  clean_multispeaker_names() |> 
  gt()

multispeaker_lines |> 
  clean_multispeaker_names() |>
  separate_longer_delim(speaker, green_circle) |> 
  gt()

```

# test7

```{r}
test7 |> 
  select(season:transcript) |> 
  # filter(season == 1) |>
  filter(type == "italics") |>
  collect() |> 
  # filter(str_detect(transcript, "Paul\'s")) |>
  filter(str_detect(transcript, "^<i>.+</i>.+$")) |> 
  # filter(str_detect(transcript, "</i>.+$")) |>
  gt()
  # peek_rows(transcript, "<i>")
```

```{r}
test7 |> 
  select(season:transcript) |> 
  unitalicize_descriptions2() |> 
  filter(str_detect(transcript, "<i>")) |>
  gt()
  # peek_rows(transcript, "Her cell phone rings and she answers")
```

```{r}
test7 |> 
  select(season:transcript) |> 
  unitalicize_descriptions2() |> 
  replace_italics2() |> 
  count(type) |> 
  collect()
```

```{r}
test7 |> 
  select(season:transcript) |> 
  collect() |> 
  unitalicize_descriptions2() |> 
  replace_italics2() |> 
  # word on either side of dash
  # filter(str_detect(transcript, "\\b[\\w]+-[\\w-]+\\b")) |> 
  # number dash number (maybe more dash and number)
  # filter(str_detect(transcript, "(\\s\\d+-\\d+)+\\s")) |> 
  filter(str_detect(transcript, "5\\-4")) |> 
  gt()
```

```{r}

dashed <- test7 |> 
  select(season:transcript) |> 
  unitalicize_descriptions2() |> 
  replace_italics2() |> 
  pull(transcript) |>
  str_extract_all("\\b[\\w]+-[\\w-]+\\b") |> 
  unlist() |>
  unique() |> 
  tibble(term = _) |> 
  mutate(
    pattern = case_when(
      str_detect(term, "(?<=(?i)Mid)-(?=(?i)Wilshire)")     ~ "Mid-Wilshire",
      str_detect(term, "(\\d)\\-([A-Z][a-z]*)\\-(\\d{1,})") ~ "call_sign",
      str_detect(term, "^\\d+-\\d+$")                 ~ "num-num",
      str_detect(term, "^\\d")                        ~ "starts_with_digit",
      str_detect(term, "^[A-Z]-")                 ~ "starts_with_letter_dash",
      str_detect(term, "^[A-Z][a-z]+-[A-Z][a-z]+")    ~ "TitleCase-TitleCase",
      str_detect(term, "-[A-Z][a-z]+-|-[A-Z][a-z]+$") ~
        "contains_TitleCase_segment",
      str_detect(term, "^[a-z]+-[a-z]+$")             ~ "lowercase-lowercase",
      TRUE                                            ~ "other"
    )
  ) |> 
  arrange(pattern, term)

dashed |> filter(pattern == "Mid-Wilshire")
dashed |> filter(pattern == "call_sign")
dashed |> filter(pattern == "contains_TitleCase_segment")
dashed |> filter(pattern == "num-num")
dashed |> filter(pattern == "TitleCase-TitleCase")
dashed |> filter(pattern == "starts_with_digit")
dashed |> filter(pattern == "starts_with_letter_dash")
dashed |> filter(pattern == "other")
dashed |> filter(pattern == "lowercase-lowercase")

dashed |> count(pattern) |> arrange(n)

```

```{r}
test7 |> 
  select(season:transcript) |> 
  unitalicize_descriptions2() |> 
  replace_italics2() |> 
  filter(str_detect(transcript, "\\d\\-[A-Z][a-z]*\\-\\d{1,}")) |> 
  mutate(
    call_sign = str_extract_all(transcript, "\\d\\-[A-Z][a-z]*\\-\\d{1,}")
  ) |> 
  unnest_longer(call_sign) |> 
  unnest_tokens(word, call_sign)

test7 |> 
  select(season:transcript) |> 
  unitalicize_descriptions2() |> 
  replace_italics2() |> 
  filter(str_detect(transcript, "\\d\\-[A-Z][a-z]*\\-\\d{1,}")) |> 
  mutate(call_sign = str_extract_all(transcript, "\\d\\-[A-Z][a-z]*\\-\\d{1,}")) |> 
  unnest_longer(call_sign) |> 
  count(call_sign) |> 
  arrange(call_sign)

test7 |> 
  select(season:transcript) |> 
  unitalicize_descriptions2() |> 
  replace_italics2() |> 
  filter(str_detect(transcript, "\\d\\-[A-Z][a-z]*\\-\\d*")) |> 
  mutate(call_sign = str_extract_all(transcript, "\\d\\-[A-Z][a-z]*\\-\\d*")) |>
  unnest_longer(call_sign) |> 
  count(call_sign) |> 
  arrange(call_sign)
```

Replace italics with symbol so that <i> and </i> don't get unnested as "i" and "i" around the italicized text.

```{r}
test7 |> 
  select(season:transcript) |> 
  unitalicize_descriptions2() |> 
  replace_italics2() |> 
  filter(str_detect(transcript, "\U1f7e9")) |>
  gt()

test7 |> 
  select(season:transcript) |> 
  unitalicize_descriptions2() |> 
  replace_italics2() |> 
  filter(str_detect(transcript, "\U1f7e9")) |>
  unnest_tokens(unnested, transcript, to_lower = FALSE) |> 
  mutate(word = unnested |> str_to_lower(), .after = unnested) |> 
  gt()
```

# test unnesting

```{r}
tribble(
  ~season, ~episode, ~transcript,
  1, 1, "I felt him die. A guy I- I was just talking to.",
  1, 2, "6-P-C-I-4-8 and a 1",
  1, 3, "	I-I'm sorry. I'm so sorry.",
  1, 4, "Wh- I- I don't understand. - Is something wrong?",
  1, 7, "Catch-22",
  1, 9, "<i>The</i> Shakespeare?",
  2, 11, "♪ Stars shining bright above you ♪",
  3, 7, "<i>Paul's_Place</i>. Yeah. That was a lifetime ago",
  3, 7, "\U2757Paul's_Place\U2757. Yeah. That was a lifetime ago",
) |> 
  unnest_tokens(word, transcript)
  # unnest_tokens(word, transcript, token = "regex", pattern = "</i>[\\s\\.]") |>
  # mutate(
  #   kind = if_else(str_detect(word, "^<i>"), "italics", NA_character_),
  #   word = word |> str_remove_all("<i>")
  # ) |>
  # unnest_tokens(word, word)
```
