---
title: "Rookie-transcripts"
format: html
execute: 
  eval: false
---

```{r}
tar_load(transcripts)
tar_load(transcripts_html)
tar_load(transcripts_lines)
tar_load(transcripts_clean)
transcripts_lines <- open_dataset(transcripts_lines, format = "parquet")
transcripts_clean <- open_dataset(transcripts_clean, format = "parquet")
```

```{r}
file.copy(
  "data/transcripts_parquet.parquet",
  "app/transcripts_parquet.parquet",
  overwrite = TRUE
)
file.copy(
  "data/transcripts_clean.parquet",
  "app/transcripts_clean.parquet",
  overwrite = TRUE
)
```

```{r}
transcripts
```

```{r}
#| label: epID-in-file-name
#| eval: false

transcript_info <- transcripts |> 
  select(season, episode, title) |> 
  mutate(
    across(1:2, as.character),
    across(1:2, \(x) if_else(str_detect(x, "^\\d$"), paste0("0", x), x)),
    prefix = str_c(season, "x", episode, "_")
  )

files <- tibble(
  file_name = list.files("data/The-Rookie", recursive = TRUE)
) |> 
  mutate(title = str_extract(file_name, "(?<=\\d/).+(?=\\.(pdf|html))"))

transcript_info <- transcript_info |> 
  left_join(files, by = join_by(title)) |> 
  mutate(
    new_name = str_c(prefix, title)
  )

transcript_info |> 
  mutate(
    old_path = file.path("data/The-Rookie", file_name),
    new_path = file.path("data/The-Rookie", dirname(file_name), str_c(new_name, ".", tools::file_ext(file_name)))
  ) |> 
  pwalk(\(old_path, new_path, ...) {
    if (file.exists(old_path)) file.rename(old_path, new_path)
  })

```

```{r}
#| label: html-to-text
#| eval: false

transcripts |>
  mutate(label = str_c("=== S", season, "E", episode, " ", title, " ===")) |>
  rowwise() |>
  mutate(block = str_c(label, transcript, sep = "\n\n")) |>
  ungroup() |>
  pull(block) |>
  str_flatten(collapse = "\n\n---\n\n") |>
  writeLines("data/The-Rookie/all_transcripts.txt")

```

```{r}
transcripts |> count(season)
```

```{r}

transcripts |> 
  mutate(
    count_Chen = str_count(transcript, "(?<!MRS\\.\\s)(?<!Mrs\\.\\s)CHEN"),
    .keep = "unused",
    .after = title
  ) |> 
  arrange(count_Chen) |> 
  select(1:6)

transcripts |> 
  mutate(count_Chen = str_count(transcript, "(?<!MRS\\.\\s)(?<!Mrs\\.\\s)CHEN"), .keep = "unused") |> 
  mutate(ep_ID = as_factor(ep_ID) |> fct_reorder(count_Chen) |> fct_rev()) |>
  ggplot(aes(ep_ID, count_Chen)) +
  geom_col() + 
  theme_light() +
  theme(axis.text.x = element_text(angle = 90, hjust = 0.5, vjust = 0.5))

```

```{r}
transcripts |> 
  mutate(
    Chen_mentions = str_count(transcript, "(?<!Mrs\\.\\s)Chen"),
    .after = title
  ) |> 
  select(1:6)

transcripts |> 
  mutate(
    count_Chen = str_count(transcript, "(?<!MRS\\.\\s)(?<!Mrs\\.\\s)CHEN"),
    Chen_mentions = str_count(transcript, "(?<!Mrs\\.\\s)Chen"),
    .keep = "unused"
  ) |> 
  # mutate(ep_ID = as_factor(ep_ID) |> fct_reorder(count_Chen) |> fct_rev()) |>
  ggplot() +
  geom_point(aes(episode_number, count_Chen), color = "blue") + 
  geom_point(aes(episode_number, Chen_mentions), color = "red") +
  geom_smooth(aes(episode_number, count_Chen), color = "blue") +
  geom_smooth(aes(episode_number, Chen_mentions), color = "red") + 
  # geom_line(aes(ep_ID, count_Chen, group = 1), color = "blue") +
  # geom_line(aes(ep_ID, Chen_mentions, group = 1), color = "red") +
  theme_light() +
  theme(axis.text.x = element_text(angle = 90, hjust = 0.5, vjust = 0.5))

```

```{r}

transcripts |> 
  mutate(
    murder = str_count(transcript, "(M|m)urder[(s|ed)]?\\s"),
    stabbing = str_count(transcript, "(S|s)tab[s|bing|bed]?\\s") +
      str_count(transcript, "(K|k)nifed"),
    assault = str_count(transcript, "(A|a)ssault[ed]?\\s"),
    suicide = str_count(transcript, "(S|s)uicid(e|al)"),
    .after = title
  )

transcripts |> 
  mutate(
    murder = str_count(transcript, "(M|m)urder[(s|ed)]?\\s"),
    stabbing = str_count(transcript, "(S|s)tab[s|bing|bed]?\\s") +
      str_count(transcript, "(K|k)nifed"),
    assault = str_count(transcript, "(A|a)ssault[ed]?\\s"),
    suicide = str_count(transcript, "(S|s)uicid(e|al)"),
    .after = title
  ) |> 
  ggplot(aes(x = ep_ID)) +
  geom_point(aes(y = murder), color = "black") +
  geom_point(aes(y = stabbing), color = "red") +
  geom_point(aes(y = assault), color = "blue") +
  geom_point(aes(y = suicide), color = "darkgreen") +
  labs(x = "Episode", y = "Number of Mentions")

```

```{r}

transcripts |> 
  mutate(
    count_Chen = str_count(transcript, "(?<!MRS\\.\\s)(?<!Mrs\\.\\s)CHEN"),
    .keep = "unused",
    .after = title
  ) |> 
  select(1:6) |> 
  group_by(season) |> 
  summarise(sum = sum(count_Chen), avg = mean(count_Chen))

```

```{r}
transcripts$transcript |> str_which("H(enry|ENRY)\\sN(olan|OLAN)")

transcripts$transcript |> str_which("M(rs|RS)\\.\\sN(olan|OLAN)")

transcripts$transcript |> str_which("S(arah|ARAH)\\sN(olan|OLAN)")

transcripts$transcript |> str_which("S(arah|ARAH)")

```

```{r}
transcripts |> 
  filter(season == 1, episode == 1) |> 
  unnest_tokens(word, transcript, to_lower = FALSE, drop = FALSE)
```

```{r}
transcripts |> 
  filter(episode_number == 1) |> 
  select(transcript)  %>% 
  .[[1]]
```

```{r}
#| label: clean-S1E1
transcripts |> 
  filter(episode_number == 1) |> 
  mutate(
    transcript = str_remove_all(transcript, "\\s*[-–]?\\s*\\[[^]]+\\]\\s*[-–]?\\s*\n*") |>
      str_remove_all("\\s*[-–]?\\s*\\([^)]+\\)\\s*[-–]?\\s*\n*") |>
      str_replace_all("\n{3,}", "\n\n") |> 
      str_split("\n\n")
  ) |> 
  unnest(transcript) |> 
  mutate(
    transcript = str_remove(transcript, "^[\\s\\-–]*"),
    rowID = row_number(),
    type = case_when(
      str_detect(transcript, "(INT|EXT)\\.") ~ 
      "scene_heading",
      str_detect(transcript, "[A-Z]+[:punct:]*[A-Z]+$") ~ "caption",
      str_detect(
        transcript,
        "^[A-Z][A-Z]+(?:[,/]\\s*[A-Z]+|\\sand\\s[A-Z]+)+(?=[A-Z\\d]{1}[a-z\\d\'\\s-]+)"
      ) ~ "dialogue_multi_speaker",
      str_detect(
        transcript, "^[A-Z][A-Z\\s]+(?=[A-Z]{1}[a-z\\d\'\\s-]+)"
      ) ~ "dialogue"
    ),
    speaker = if_else(
      type == "dialogue" | type == "dialogue_multi_speaker",
      str_extract(
        transcript,
        "^[A-Z][A-Z\\s,/]+(?:\\sand\\s[A-Z]+)*(?=[A-Z\\d]{1}[a-z\\d\'\\s-]+)"
      ),
      NA_character_
    ),
    transcript = if_else(
      type == "dialogue" | type == "dialogue_multi_speaker",
      str_remove(
        transcript,
        "^[A-Z][A-Z\\s,/]+(?:\\sand\\s[A-Z]+)*(?=[A-Z\\d]{1}[a-z\\d\'\\s-]+)"
      ),
      transcript
    ),
    scene = case_when(
      type == "scene_heading" & str_detect(transcript, "EXT\\.") ~ "EXT",
      type == "scene_heading" & str_detect(transcript, "INT\\.") ~ "INT"
    )
  ) |> 
  separate_longer_delim(speaker, delim = regex("(,\\s|\\sand\\s|/)")) |> 
  select(type, speaker, scene, transcript)
```

```{r}
#| label: clean-S1E6

transcripts |> 
  filter(episode_number == 6) |> 
  mutate(
    transcript = str_remove_all(transcript, "\\s*[-–]?\\s*\\[[^]]+\\]\\s*[-–]?\\s*\n*") |>
      str_remove_all("\\s*[-–]?\\s*\\([^)]+\\)\\s*[-–]?\\s*\n*") |>
      str_replace_all("\n{3,}", "\n\n") |> 
      str_split("\n\n")
  ) |> 
  unnest(transcript) |> 
  mutate(
    transcript = str_remove(transcript, "^[\\s\\-–]*"),
    rowID = row_number(),
    type = case_when(
      str_detect(transcript, "(INT|EXT)\\.") ~ 
      "scene_heading",
      str_detect(transcript, "[A-Z]+[:punct:]*[A-Z]+$") ~ "caption",
      str_detect(
        transcript,
        "^[A-Z][A-Z]+(?:[,/]\\s*[A-Z]+|\\sand\\s[A-Z]+)+(?=\"|[A-Z\\d]{1}[a-z\\d\'\\s-]+)"
      ) ~ "dialogue_multi_speaker",
      str_detect(
        transcript, "^[A-Z][A-Z\\s]+(?=\"|[A-Z\\d]{1}[a-z\\d\'\\s-]+)"
      ) ~ "dialogue",
      TRUE ~ "other"
    ),
    speaker = if_else(
      type == "dialogue" | type == "dialogue_multi_speaker",
      str_extract(
        transcript,
        "^[A-Z][A-Z\\s,/\\.]+(?:\\sand\\s[A-Z]+)*(?=\"|[A-Z\\d\"]{1}[a-z\\d\'\\s-]+)"
      ),
      NA_character_
    ),
    transcript = if_else(
      type == "dialogue" | type == "dialogue_multi_speaker",
      str_remove(
        transcript,
        "^[A-Z][A-Z\\s,/\\.]+(?:\\sand\\s[A-Z\"]+)*(?=\"|[A-Z\\d\"]{1}[a-z\\d\'\\s-]+)"
      ),
      transcript
    ),
    scene = case_when(
      type == "scene_heading" & str_detect(transcript, "EXT\\.") ~ "EXT",
      type == "scene_heading" & str_detect(transcript, "INT\\.") ~ "INT"
    )
  ) |> 
  separate_longer_delim(speaker, delim = regex("(,\\s|\\sand\\s|/)")) |> 
  select(type, speaker, scene, transcript)
```

```{r}
#| label: check-string
transcripts |> 
  filter(episode_number == 6) |> 
  mutate(
    transcript = str_remove_all(transcript, "\\s*[-–]?\\s*\\[[^]]+\\]\\s*[-–]?\\s*\n*") |>
      str_remove_all("\\s*[-–]?\\s*\\([^)]+\\)\\s*[-–]?\\s*\n*") |>
      str_replace_all("\n{3,}", "\n\n")
  )  %>% 
  .[[6]] |> 
  str_sub(26800, 27467)
```


```{r}
#| label: check-rows
transcripts |> 
  filter(episode_number == 6) |> 
  mutate(
    transcript = str_remove_all(transcript, "\\s*[-–]?\\s*\\[[^]]+\\]\\s*[-–]?\\s*") |>
      str_remove_all("\\s*[-–]?\\s*\\([^)]+\\)\\s*[-–]?\\s*") |>
      str_replace_all("\n{3,}", "\n\n") |> 
      str_split("\n\n")
  ) |> 
  unnest(transcript) |> 
  pull(transcript)
```

```{r}
#| label: count-other
transcripts_clean |> 
  filter(type == "other") |> 
  group_by(season) |>
  count(type) |> 
  collect()

```

```{r}
#| label: check-other

transcripts_clean |> 
  filter(type == "other") |>
  mutate(start = str_sub(transcript, 1, 60)) |>
  group_by(season, episode) |> 
  count(start, sort = TRUE) |>
  arrange(season, episode) |> 
  collect()

```

```{r}
#| label: list-patterns

dialogue_patterns <- c(
  "^[A-Z][A-Z\\s]+(?=[A-Z]{1}[a-z]+)",    # regular
  "^[A-Z][A-Z\\s]+(?=\\d)",               # digit
  "^[A-Z][A-Z\\s]+(?=\")",                # quotation mark
  "^[A-Z][A-Z\\.\\s]+[A-Z]{1}[a-z]+",     # titles (Mrs/Mr/Dr)
  "^", # OK
  "^[A-Z][A-Z\\s]+(?=([A-Z]{1}\\.)+\\s)", # acronyms
  # Irish Mc/Mac
  "^[A-Z][A-Z\\s]+(?=[A-Z]{1}[a-z:\\s]+)" # end speaker with colon\\s
  
)

matches_any <- function(x, patterns) {
  map(patterns, \(p) str_detect(x, p)) |>
    reduce(`|`)
}

patterns_names <- c(
  "[A-Z][A-Z\\s]+",            # regular
  # multiple speakers separated by comma
  # multiple speakers separated by "and"
  # multiple speakers separated by comma and &
  "[A-Z][A-Z\\.\\s]+",         # titles
  # D.S. Caradine / M.E. Lowell
  # R.J.
  "[A-Z][a-z]+[A-Z]+",    # Irish surnames
  "[A-Z]+\'s\\s[A-Z]+",        # possessive (e.g., Wendell's mom)
  "([A-Z]+\\.)+",               # name with periods (e.g., WILL.I.AM)
                               # name with apostrophe (e.g., D'Andre)
                               # name with hyphen/dash
                               # name that is or starts with acronym
                               # call sign
  "[:alnum:][A-Z\\s]+"         # digit CHECKED
                               # 	911 OPERATOR
)

patterns_separators <- c(
                       # regular (nothing)
  "(?=:\\s)?",          # colon and space
  "(?=\\.\\s)?"         # leftover whitespace
  
)

patterns_dialogue_start <- c(
 "(?=[A-Z][a-z\\s]*)",    # regular
 "(?=\\d+)",           # digit
 "(?=\")",             # quotation mark
 "(?=[A-Z][a-z\']+)",  # contraction
 "(?=[A-Z][a-z,]+)",  # word then comma
 "(?=OK[\\.\,])",      # "OK."
 "(?=[A-Z]\\.)",       # acronyms w/ letters separated by period
 
 "(?=\\$)",             # dollar sign CHECKED
 
                       # list (A, ...)
 "(?=[\\.]{3})",       # starts with ellipsis CHECKED
 "(?=♪\\s)",           # music
)

patterns <- crossing(
  name = patterns_names,
  sep = patterns_separators,
  start = patterns_dialogue_start
) |>
  mutate(pattern = str_c("^", name, sep, start)) |>
  pull(pattern)

patterns

```

```{r}
#| label: clean

transcripts |> 
  filter(season == 1, episode == 2) |> 
  clean_transcripts() |> 
  filter(type == "other") |> 
  select(type, speaker, transcript)

transcripts |> 
  filter(season == 3, episode == 8) |> 
  clean_transcripts() |> 
  filter(type == "other") |> 
  select(type, speaker, transcript) |> 
  mutate(matched = case_when(
    # str_detect(transcript, "^[A-Z][A-Z]+(?=\\$)") ~ "yes",
    # str_detect(transcript, "^[A-Z][A-Z\\s]+(?=[\\.]{3})") ~ "yes",
    # str_detect(transcript, "^[A-Z0-9][A-Z\\s]+(?=[A-Z][a-z\\s-]+)") ~ "yes",
    TRUE ~ "no"
  ))

```

```{r}
transcripts_clean |> 
  filter(type == "other") |>
  mutate(start = str_sub(transcript, 1, 60)) |>
  group_by(season, episode) |> 
  count(start, sort = TRUE) |>
  arrange(season, episode) |> 
  filter(str_detect(start, "'")) |> 
  collect() 
```

```{r}
#| label: examples

examples <- read_csv("
example
NOLANThanks
CHEN, NOLAN, WESTYes
BISHOP and LOPEZShut
CHEN, NOLAN, & WESTAnd
DR. SAWYER
MRS. LOPEZHello
McAVOYTook
MacEXAMPLEHello
WENDELL’S MOMCan
WILL.I.AMExcuse
D'ANDRESee?
J-BAGMom
S.W.A.T. LEADERThey're
6-MARY-100Copy
3EYEZW-W-What?
NOLANThanks
BRADFORD/CHEN: Yeah.
CHEN7-ADAM-19
NOLAN\"They\"?
3EYEZIt's not
CHENI'm example
CHENDon’t example
NOLANI, um I do have a,
NOLANYou, um example
LOPEZA, I had
CHENOK. How's
CHENOK, example
WESTL.A.P.D.
WESTLAPD
BISHOP$21,000
NOLAN...I think
RODGE♪ You") |> 
  mutate(
    rowID = row_number(),
    type = case_when(
      rowID %in% 1:15  ~ "name",
      rowID %in% 16:17 ~ "sep",
      rowID %in% 18:32 ~ "start"
    )
  ) |> 
  relocate(type, .after = example)

examples

```

```{r}

examples |> 
  mutate(
    
  )

```

```{r}
#| label: test

name_patterns <- c(
  "^[A-Z]{2,}",                    # NOLAN, CHEN
  "^(?:DR|MRS|MR)\\.[\\s]?[A-Z]+", # DR. SAWYER, MRS. LOPEZ
  "^Mc[A-Z][A-Z]+",                 # McAVOY
  "^Mac[A-Z][A-Z]+",                # MacEXAMPLE
  "^[A-Z]+\\'S\\s[A-Z]+",           # WENDELL'S MOM
  "^[A-Z]+\\.[A-Z]+\\.[A-Z]+",      # WILL.I.AM
  "^D\\'[A-Z]+",                    # D'ANDRE
  "^[A-Z]\\-[A-Z]+",                # J-BAG
  "^S\\.W\\.A\\.T\\.\\s[A-Z]+",     # S.W.A.T. LEADER
  "^\\d\\-[A-Z]+\\-\\d+",           # 6-MARY-100
  "^\\d[A-Z]+"                      # 3EYEZ
)

separator_patterns <- c(
  "",          # nothing - NOLANThanks
  ":\\s",      # colon space - BRADFORD/CHEN: Yeah
  "/",         # slash - BRADFORD/CHEN
  ","          # comma - CHEN, NOLAN
)

dialogue_start_patterns <- c(
  "[A-Z][a-z]",   # Thanks, Hello
  "[a-z]",         # yeah
  "\\d",           # 7-ADAM-19, $300, 3EYEZ
  "\"",            # "They"?
  "\\$",           # $21,000
  "\\.\\.\\.",     # ...I think
  "[A-Z]{2,}",     # LAPD
  "[A-Z]\\.",      # L.A.P.D
  "OK",            # OK. How's, OK, example
  "[A-Z],",        # A, I had
  "♪",             # ♪ You
  "[A-Z]\\s"       # I, um
)

matches_any <- function(x, patterns) {
  map(patterns, \(p) str_detect(x, p)) |>
    reduce(`|`)
}

all_patterns <- crossing(
  name = name_patterns,
  sep = separator_patterns,
  start = dialogue_start_patterns
) |>
  mutate(pattern = str_c(name, sep, start)) |>
  pull(pattern)

test <- transcripts |> 
  mutate(
      transcript = str_remove_all(transcript, "\\s*[-–]?\\s*\\[[^]]+\\]\\s*[-–]?\\s*\n*") |>
        str_remove_all("\\s*[-–]?\\s*\\([^)]+\\)\\s*[-–]?\\s*\n*") |>
        str_replace_all("\n{3,}", "\n\n") |> 
        str_split("\n\n")
    ) |> 
    unnest(transcript) |> 
    mutate(
      transcript = str_remove(transcript, "^[\\s\\-–]*"),
      rowID = row_number(),
      type = case_when(
        str_detect(transcript, "^(INT|EXT)\\.") ~ "scene_heading",
        str_detect(transcript, "^[A-Z][A-Z\\s\\d:,\\.!-]+$") ~ "caption",
        matches_any(transcript, all_patterns) ~ "dialogue",
        TRUE ~ "other"
      ),
      scene = case_when(
        type == "scene_heading" & str_detect(transcript, "EXT\\.") ~ "EXT",
        type == "scene_heading" & str_detect(transcript, "INT\\.") ~ "INT"
      )
    )

test |> write_parquet("data/The-Rookie/test.parquet")
test <- open_dataset("data/The-Rookie/test.parquet")

```

```{r}
test |> 
  filter(type == "other") |>
  # filter(str_detect(transcript, "CARADINE")) |>
  # filter(ep_ID == 1 & str_starts(transcript, "L")) |>
  select(season, episode, type, transcript) |> 
  collect()

test |> 
  filter(season == 1, episode == 1, str_starts(transcript, "L")) |> 
  collect()
```

```{r}
#| label: test2

full_pattern <- paste(
  "^[A-Z0-9][A-Z0-9\\s\\.\\-\\'#&,/]+(?=[\"$♪'\\.a-z]|[A-Z][\\s-]|\\d(?![-A-Z#]))",
  "^ACTOR![A-Z]+(?=[\"$♪'\\.a-z]|[A-Z][\\s-]|\\d(?![-A-Z]))",
  "^[A-Z][a-z]{1,2}[A-Z]+(?=[\"$♪'\\.a-z]|[A-Z][\\s-]|\\d(?![-A-Z#]))",
  sep = "|"
)

transcripts |> 
  mutate(
    transcript = transcript |> 
      str_remove_all("\\s*[-–]?\\s*\\[[^]]+\\]\\s*[-–]?\\s*\n*") |>
      str_remove_all("\\s*[-–]?\\s*\\([^)]+\\)\\s*[-–]?\\s*\n*") |>
      str_replace_all("\n{3,}", "\n\n") |> 
      str_replace_all("[^\n]\n{1}(?=[^\n])", "\n\n") |>
      str_replace_all("(\u201c|\u201d)", "\"") |>
      str_replace_all("\u2018|\u2019", "'") |>
      str_remove_all("\u2028") |> 
      # Cleaning needs to go before splitting
      str_split("\n\n")
  ) |> 
  unnest(transcript) |> 
  filter_out(transcript == "") |> 
  mutate(
    transcript = str_remove(transcript, "^[\\s\\-–]*"),
    rowID = row_number(),
    type = case_when(
      transcript %in% captions ~ "caption",
      str_detect(transcript, "(INT|EXT)(\\.|,)") ~ "scene_heading",
      str_detect(transcript, "PATROL\\sCAR") ~ "scene_heading",
      str_detect(transcript, "^ACTOR![A-Z]+") ~ "dialogue_recorded",
      str_detect(transcript, all_caps_pattern) ~ "dialogue",
      str_detect(transcript, full_pattern) ~ "dialogue",
      str_detect(transcript, "Previously\\son\\s(\"?The Rookie\"?|THE\\sROOKIE|\\.{3})") ~ "other"
    ),
    scene = case_when(
      type == "scene_heading" & str_detect(transcript, "EXT") ~ "EXT",
      type == "scene_heading" & str_detect(transcript, "INT") ~ "INT",
      type == "scene_heading" & str_detect(transcript, "PATROL\\sCAR") ~ "shop"
    )
  ) |> 
  mutate(line = row_number(), .by = c(season, episode), .after = episode) |> 
  write_parquet("data/The-Rookie/test2.parquet")

test2 <- open_dataset("data/The-Rookie/test2.parquet")

```

```{r}
#| label: count-type

test2 |> count(type) |> collect()

```

```{r}
#| label: type-na

test2 |>
  filter(is.na(type)) |>
  select(season, episode, line, type, transcript) |>
  collect()

```

```{r}
test2 |> 
  filter(str_detect(transcript, "^Previously\\son\\s")) |> 
  select(season, episode, line, type, transcript) |> 
  collect() |> 
  print(n=38)
```


```{r}

test2 |>
  collect() |>
  mutate(
    next_transcript = lead(transcript),
    next_type = lead(type),
    prev_type = lag(type)
  ) |>
  filter(
    # Rows that look like orphaned speaker names:
    # short, all-caps, no dialogue text detected
    type == "dialogue" & !str_detect(transcript, "[a-z\"'♪$]") |
    # Rows with dialogue but no speaker detected:
    is.na(type) & prev_type == "dialogue"
  ) |>
  select(rowID, season, episode, line, prev_type, type, next_type, transcript, next_transcript) |> 
  slice_head(n = 40) |> 
  vis_miss()

```

```{r}
#| label: test3

test3 <- transcripts_clean |> 
  mutate(
    type = replace_when(
      type, 
      str_detect(transcript, "\u266a") ~ "lyrics"
    )
  )

```

```{r}
#| label: count-type

test3 |> count(type) |> collect()

```

```{r}
#| label: type-na

test3 |> 
  filter(is.na(type)) |> 
  select(all_of(preview_columns)) |> 
  collect()

```

```{r}

transcripts_html |> 
  mutate(
    transcript = transcript |> 
      str_remove_all("<i>(?=\u266a)")
  )

```

```{r}
#| label: test-first-last-lines

transcripts_clean |> 
  select(ep_ID, line, transcript) |> 
  collect() |> 
  group_by(ep_ID) |> 
  filter(line %in% c(1, 2, max(line) - 1, max(line)))

```

```{r}
#| label: test2a

full_pattern <- paste(
  "^[A-Z0-9][A-Z0-9\\s\\.\\-\\'#&,/]+(?=[\"$♪'\\.a-z]|[A-Z][\\s-]|\\d(?![-A-Z#]))",
  "^ACTOR![A-Z]+(?=[\"$♪'\\.a-z]|[A-Z][\\s-]|\\d(?![-A-Z]))",
  "^[A-Z][a-z]{1,2}[A-Z]+(?=[\"$♪'\\.a-z]|[A-Z][\\s-]|\\d(?![-A-Z#]))",
  sep = "|"
)

transcripts |> 
  mutate(
    transcript = transcript |> 
      str_replace_all("\n{3,}", "\n\n") |> 
      str_replace_all("[^\n]\n{1}(?=[^\n])", "\n\n") |>
      str_replace_all("(\u201c|\u201d)", "\"") |>
      str_replace_all("\u2018|\u2019", "'") |>
      str_remove_all("\u2028") |> 
      # Cleaning needs to go before splitting
      str_split("\n\n")
  ) |> 
  unnest(transcript) |> 
  mutate(
    transcript = transcript |> 
      str_remove_all("\\s*[-–]?\\s*\\[[^]]+\\]\\s*[-–]?\\s*\n*") |>
      str_remove_all("\\s*[-–]?\\s*\\([^)]+\\)\\s*[-–]?\\s*\n*") |>
      str_remove("^[\\s\\-–]*")
  ) |> 
  filter_out(transcript == "") |> 
  mutate(
    rowID = row_number(),
    transcript = transcript |> 
      str_replace("(^[A-Z0-9][A-Z0-9\\s\\.\\-\\'#&,/]+):\\s", "\\1") |> 
      str_replace(
        "^([A-Z][a-zA-Z0-9\\s#/,]+):\\s",
        \(x) str_remove(str_to_upper(x), ":\\s")
      ),
    type = case_when(
      transcript %in% captions ~ "caption",
      str_detect(transcript, "(INT|EXT)(\\.|,)") ~ "scene_heading",
      str_detect(transcript, "PATROL\\sCAR") ~ "scene_heading",
      str_detect(transcript, "^ACTOR![A-Z]+") ~ "dialogue_recorded",
      str_detect(transcript, all_caps_pattern) ~ "dialogue",
      str_detect(transcript, full_pattern) ~ "dialogue",
      str_detect(transcript, "Previously\\son\\s(\"?The Rookie\"?|THE\\sROOKIE|\\.{3})") ~ "other"
    ),
    scene = case_when(
      type == "scene_heading" & str_detect(transcript, "EXT") ~ "EXT",
      type == "scene_heading" & str_detect(transcript, "INT") ~ "INT",
      type == "scene_heading" & str_detect(transcript, "PATROL\\sCAR") ~ "shop"
    )
  ) |> 
  mutate(line = row_number(), .by = c(season, episode), .after = episode) |> 
  write_parquet("data/The-Rookie/test2a.parquet")

test2a <- open_dataset("data/The-Rookie/test2a.parquet")

```

```{r}
test2a |> count(type) |> collect()
```

```{r}
test2a |> 
  filter(is.na(type)) |> 
  select(all_of(preview_columns)) |> 
  collect()

test2a |> 
  filter(is.na(type)) |> 
  select(all_of(preview_columns)) |> 
  group_by(season, episode) |> 
  count() |> 
  collect()
```

```{r}

test2a |> 
  select(all_of(preview_columns)) |> 
  filter(
    str_detect(transcript, "BRADFORD/CHEN:\\sYeah") |
      str_detect(transcript, "^Man:") |
      str_detect(transcript, "^Man\\s#2:\\s")
  ) |> 
  collect() |> 
  mutate(
    transcript = transcript |> 
      str_replace("(^[A-Z0-9][A-Z0-9\\s\\.\\-\\'#&,/]+):\\s", "\\1") |> 
      str_replace(
        "^([A-Z][a-zA-Z0-9\\s#/,]+):\\s",
        \(x) str_remove(str_to_upper(x), ":\\s")
      )
  )

test2a |> 
  select(all_of(preview_columns)) |> 
  collect() |> 
  filter(type == "dialogue", str_starts(transcript, "MAN"))

```

```{r}
#| label: rm-italics

transcripts_html$transcript[8] |> 
  str_remove_all("<i>(?=Previously\\son\\s(\"?The Rookie\"?|THE\\sROOKIE|\\.{3}).+?[</i>])") |> 
  str_remove_all("(?<=Previously\\son\\s(\"?The Rookie\"?|THE\\sROOKIE|\\.{3}).+?)</i>")

```

```{r}
transcripts_lines |> 
  select(season, episode, transcript) |> 
  filter(str_detect(
          transcript,
          "Previously\\son\\s(\"?The Rookie\"?|THE\\sROOKIE)"
        )) |> 
  collect()
```

```{r}
transcripts_lines |> 
  select(season, episode, transcript) |> 
  collect() |> 
  mutate(
    type = case_when(
      transcript %in% captions ~ "caption",
      str_detect(
        transcript,
        "Previously\\son\\s(\"?The Rookie\"?|THE\\sROOKIE)"
      ) ~ "previously"
    ),
    transcript = if_else(
      type == "previously",
      transcript |> 
        str_remove("\\.{3}") |> 
        str_remove_all("</?i>") |> 
        str_remove(":$") |>
        str_replace("(?<=\\s)The\\sRookie|THE\\sROOKIE", "\"The Rookie\"") |> 
        str_remove("ANNOUNCER"),
      transcript
    )
  ) |> 
  filter(type == "previously" | type == "caption")

transcripts_lines |> 
  select(season, episode, transcript) |>  
  filter(str_detect(
          transcript,
          "Previously\\son\\s(\"?The Rookie\"?|THE\\sROOKIE)"
        )) |> 
  collect() |> 
  mutate(
    transcript = transcript |> 
      str_replace(
        "^.+Previously\\son\\s(\"?The Rookie\"?|THE\\sROOKIE)[\\.{3}|:]?",
        "Previously on \"The Rookie\""
      ) |> 
      str_remove("\\.{3}")
  ) 

transcripts_lines |> 
  select(season, episode, transcript) |>  
  filter(str_detect(
          transcript,
          "Previously\\son\\s(\"?The Rookie\"?|THE\\sROOKIE)"
        )) |> 
  collect() |> 
  mutate(
    transcript = transcript |> 
      str_remove("\\.{3}") |> 
      str_remove_all("</?i>") |> 
      str_remove(":$") |>
      str_replace("(?<=\\s)The\\sRookie|THE\\sROOKIE", "\"The Rookie\"") |> 
      str_remove("ANNOUNCER")
  )
```

```{r}
#| label: lyrics 

transcripts_lines |> 
  select(season, episode, transcript) |> 
  collect() |> 
  mutate(
    type = case_when(
      str_detect(transcript, "\u266a") ~ "lyrics",
      transcript %in% captions ~ "caption"
    ),
    transcript = case_when(
      type == "lyrics" ~ transcript |> 
        str_remove_all("</?i>"),
      .default = transcript
    )
  ) |> 
  mutate(
    transcript = transcript |> 
      str_split("\u266a{2}|(\u266a\\s/\\s\u266a)")
  ) |> 
  unnest(transcript) |> 
  mutate(transcript = transcript |> str_remove_all("\u266a\\s?")) |> 
  filter(type == "lyrics")

# |> 
#   mutate(split = transcript |> str_split("\u266a{2}|(\u266a\\s/\\s\u266a)")) |> 
#   unnest(split) |> 
#   relocate(type, .after = last_col()) |> 
#   mutate(split = split |> str_remove_all("\u266a\\s?"))

```

```{r}
#| label: brackets-parentheses

transcripts_lines |> 
  select(season, episode, transcript) |> 
  filter(str_detect(transcript, "[\\(\\)\\[\\]]")) |> 
  collect() |> 
  mutate(
    edited = transcript |> 
      str_remove_all("(?=\\s?)\\([^\\)]+\\)\\s?") |> 
      str_remove_all("(?=\\s?)\\[[^]]+\\]\\s?")
  ) |> 
  filter_out(str_starts(transcript, "<i>")) |> 
  filter(season == 2, episode == 7, str_starts(transcript, "CHEN")) |> 
  mutate(
    edited = str_remove(edited, "(?<=[A-Z])\\s{1}(?=[\"$♪\'\\.a-z]|[A-Z][\\s-]|\\d(?![-A-Z#]))")
  )


transcripts_lines |> 
  select(season, episode, transcript) |> 
  filter(str_detect(transcript, "[\\(\\)\\[\\]]")) |> 
  collect() |> 
  mutate(
    edited = transcript |> 
      str_remove_all("(?<=[A-Z])\\s?\\([^)]+\\)\\s?") |>
      str_remove_all("(?<=[A-Z])\\s?\\[[^]]+\\]\\s?") |> 
      str_remove_all("(?=\\s?)\\([^\\)]+\\)\\s?") |> 
      str_remove_all("(?=\\s?)\\[[^]]+\\]\\s?")
  ) |> 
  filter_out(str_starts(transcript, "<i>")) |> 
  filter(str_detect(transcript, "<i>"))

```

```{r}
#| label: unicode

transcripts_lines |> 
  select(season, episode, transcript) |> 
  # filter(str_detect(transcript, "\u2018")) |> 
  collect()

```

```{r}
#| label: transcripts-clean

tar_load(transcripts_clean)
transcripts_clean <- open_dataset(transcripts_clean, format = "parquet")

transcripts_clean |> 
  select(season, episode, type, transcript) |> 
  count(type) |> 
  collect()

transcripts_clean |> 
  select(season, episode, type, transcript) |> 
  filter(is.na(type)) |> 
  collect()

clean_w_italics <- transcripts_clean |> 
  select(ep_number, season, episode, line, type, transcript) |> 
  filter(str_detect(transcript, "</?i>")) |> 
  collect() |> 
  mutate(edited = transcript |> str_remove_all("</?i>"))

clean_w_italics

```

```{r}
#| label: test4

test4 <- transcripts_lines |> 
  select(season, episode, transcript) |> 
  collect() |> 
  mutate(
    # remove ":\\s" separating name and dialogue; converts lower to upper
    transcript = transcript |> 
      str_replace("(^[A-Z0-9][A-Z0-9\\s\\.\\-\\'#&,/]+):\\s", "\\1") |> 
      str_replace(
        "^([A-Z][a-zA-Z0-9\\s#/,]+):\\s",
        \(x) str_remove(str_to_upper(x), ":\\s")
      ) |> 
      # remove descriptions denoted by [] and ()
      str_remove_all("(?<=[A-Z])\\s?\\([^)]+\\)\\s?") |>
      str_remove_all("(?<=[A-Z])\\s?\\[[^]]+\\]\\s?") |> 
      str_remove_all("(?=\\s?)\\([^\\)]+\\)\\s?") |> 
      str_remove_all("(?=\\s?)\\[[^]]+\\]\\s?")
  ) |> 
  mutate(
    # identify "Previously on..."
    type = case_when(
      str_detect(
        transcript,
        "Previously\\son\\s(\"?The Rookie\"?|THE\\sROOKIE)"
      ) ~ "previously",
      # identify song lyrics
      str_detect(transcript, "\u266a") ~ "lyrics"
    ),
    # clean "Previously on..." lines; remove "</?i>"
    transcript = case_when(
      type == "previously" ~ transcript |> 
        str_remove("\\.{3}") |> 
        str_remove_all("</?i>") |> 
        str_remove(":$") |>
        str_replace("(?<=\\s)The\\sRookie|THE\\sROOKIE", "\"The Rookie\"") |> 
        str_remove("ANNOUNCER"),
      .default = transcript
    )
  ) |> 
  filter_out(str_starts(transcript, "<i>")) |> 
  mutate(
    type = case_when(
      transcript %in% captions ~ "caption",
      str_detect(transcript, "(INT|EXT)(\\.|,)") ~ "scene_heading",
      str_detect(transcript, "PATROL\\sCAR") ~ "scene_heading",
      str_detect(transcript, "^ACTOR![A-Z]+") ~ "dialogue_recorded",
      str_detect(transcript, all_caps_pattern) ~ "dialogue",
      str_detect(transcript, full_pattern) ~ "dialogue",
      .default = type
    )
  ) |> 
  filter_out(transcript == "") |> 
  mutate(transcript = transcript |> str_remove_all("</?i>"))

```

```{r}
test4 |> 
  count(type)
  # filter(is.na(type))
  # filter(type == "previously")
  # filter(type == "caption")
```

```{r}
#| label: first-last-lines

transcripts_clean |> group_by(season, episode) |> count(episode) |> collect()

transcripts_html$transcript |> str_trunc(100)

peek_first_last_lines(transcripts_clean) |> 
  filter(line == 1) |> 
  print(n=144)

peek_first_last_lines(transcripts_clean) |> 
  filter(line %in% 1:2) |> 
  print(n=288)

peek_first_last_lines(transcripts_clean, 3) |> 
  filter(line %in% 1:3) |> 
  print(n=432)

peek_first_last_lines(transcripts_clean, 3) |> 
  # filter(season == 1, episode %in% 1:5) |>
  filter(line %in% 1:3) |>
  filter_out(str_detect(transcript, "Season\\s\\d,\\s(E|e)pisode\\s\\d")) |>
  # print(n=70)
  # print(n=144)
  print(n=288)

```

```{r}
transcripts |> pull(html) |> str_trunc(100)

transcripts |> 
  select(season, episode, html) |> 
  mutate(html = html |> 
           str_replace_all("(\u201c|\u201d)", "\"") |>
           str_replace_all("\u2018|\u2019", "'") |>
           str_remove_all("\u2028")
  ) |> 
  mutate(
    cut = html |> str_remove(
      "^(THE\\sROOKIE[\\s\\S]+?\"[^\"\\n]+\"[^\\S\\n]*\\n+|[\\s\\n]+)"
    ) |> 
      str_remove("^(THE\\sROOKIE[\\s\\S]+?\"[^\"\\n]+\"[^\\S\\n]*\\n+|[\\s\\n]+)")
  )
```

```{r}

transcripts_lines |> 
  select(season, episode, transcript) |> 
  filter(season == 2, episode == 5) |> 
  collect() |> 
  filter_out(str_starts(transcript, "<i>")) |> 
  mutate(type = case_when(str_detect(transcript, "(INT|EXT)\\.") ~ "scene_heading")) |> 
  pivot_wider(id_cols = transcript, names_from = "^[A-Z]+(?=[A-Z][a-z[:punct:])")

transcripts_clean |> 
  filter(season == 2, episode == 5) |> 
  collect() |> 
  mutate(
    type = case_when(str_detect(transcript, "(INT|EXT)\\.") ~ "scene_heading"),
    is_speaker = if_else(
      is.na(type),
      str_detect(transcript, "^[A-Z][A-Z0-9\\s\\.\\-\\'#&,/]+$"),
      FALSE
    ),
    is_break = is_speaker | !is.na(type),
    group_id = cumsum(is_break)
  ) |> 
  summarise(
    speaker = first(transcript[is_speaker]),
    transcript = transcript[!is_speaker] |> str_flatten(collapse = " "),
    type = first(type),
    .by = c(season, episode, group_id)
  ) |> 
  mutate(line = row_number(), type = replace_when(type, !is.na(speaker) ~ "dialogue")) |> 
  select(-group_id) |> 
  relocate(c(line, type), .after = episode)

transcripts_lines |> 
  filter(season == 2, episode == 5) |> 
  collect() |> 
  filter_out(str_starts(transcript, "<i>")) |> 
  mutate(line = row_number()) |> 
  mutate(
    type = case_when(str_detect(transcript, "(INT|EXT)\\.") ~ "scene_heading"),
    is_speaker = if_else(is.na(type), str_detect(transcript, "^[A-Z][A-Z0-9\\s\\.\\-\\'#&,/]+$"), FALSE),
    group_id = cumsum(is_speaker)
  ) |> 
  summarise(
    line = first(line),
    speaker = first(transcript[is_speaker]),
    transcript = transcript[!is_speaker] |> str_flatten(collapse = " "),
    type = first(type),
    .by = c(season, episode, group_id)
  ) |> 
  select(-group_id) |> 
  filter(is.na(type) & str_detect(transcript, "INT|EXT"))

```

```{r}

transcripts_clean |> 
  count(type) |> 
  collect()

transcripts_clean |> 
  count(speaker) |> 
  collect()

transcripts_clean |> 
  select(season, episode, type, transcript) |> 
  collect() |> 
  filter(str_detect(transcript, "(INT|EXT)(\\.|,)|PATROL\\sCAR")) |> 
  nrow()

transcripts_clean |> 
  select(season, episode, type, transcript) |> 
  filter(type == "previously") |> 
  collect()

transcripts_clean |> 
  select(season, episode, type, transcript, speaker) |> 
  filter(str_detect(transcript, "Previously")) |> 
  collect()

# transcripts_clean |> 
#   select(season, episode, type, transcript, speaker) |> 
#   filter(season == 2, episode == 1) |> 
#   collect()

# transcripts_clean |> 
#   select(season, episode, type, speaker, transcript) |>
#   filter(type == "lyrics") |> 
#   collect()
# 
transcripts_lines |>
  select(season, episode, transcript) |>
  filter(season == 2, episode == 1) |>
  collect()

# transcripts_lines |> 
#   select(season, episode, transcript) |> 
#   filter(season == 2, episode == 11) |>
#   collect()

transcripts_lines |> 
  select(season, episode, transcript) |> 
  filter(str_detect(transcript, "Previously") & str_detect(transcript, "(?i)Rookie")) |>
  collect() |> 
  semi_join(
    transcripts_clean |> 
      select(season, episode, type, transcript) |> 
      filter(type == "previously") |> 
      collect(), 
    by = join_by(season, episode)
  )

```

```{r}

transcripts_clean |> 
  select(season, episode, type, speaker, transcript) |> 
  collect() |> 
  separate_wider_regex(
    speaker,
    patterns = c(
      speaker_start = "^[A-Za-z0-9'-\\.]+\\s?[A-Z]*",
      speaker_end   = "\\s[A-Za-z'-0-9]+$"
    ),
  too_few = "align_start",
  cols_remove = FALSE
  ) |> 
  mutate(
    speaker_end = if_else(is.na(speaker_end), speaker_start, speaker_end),
    speaker_start = case_when(
      str_equal(speaker_start, speaker_end) ~ NA_character_,
      .default = speaker_start
    )
  )

# "^[A-Za-z0-9\\.'\\s]+\\s?[[A-Z#\\d]+]?"
# "^[A-Za-z0-9'-\.]+\s?[A-Z]+"

# speaker_start = "^[A-Z]+[\\s[A-Z\\s]]+",
#       speaker_end   = "[A-Z]*\\s[A-Z]+$"

```

```{r}

transcripts_clean |>
  select(
    season, episode, type,
    speaker, speaker_start, speaker_end,
    transcript
  ) |> 
  collect() |> 
  filter(speaker_end %in% str_to_upper(characters$last_name)) |> 
  count(speaker_end, sort = TRUE)

transcripts_clean |>
  select(
    season, episode, type,
    speaker, speaker_start, speaker_end,
    transcript
  ) |> 
  collect() |> 
  filter(speaker_end %in% str_to_upper(characters$last_name)) |> 
  count(season, sort = TRUE)

sum_lines <- transcripts_clean |>
  select(
    season, episode, type,
    speaker, speaker_start, speaker_end,
    transcript
  ) |> 
  collect() |> 
  filter(speaker_end %in% str_to_upper(characters$last_name)) |> 
  filter(speaker_end %in% c("NOLAN", "CHEN", "BRADFORD", "HARPER", "GREY", "LOPEZ")) |> 
  group_by(season) |>
  count(speaker_end) |> 
  mutate(
    season = as.character(season),
    speaker_end = fct_reorder(speaker_end, desc(n)),
    sum = sum(n),
    prop = n / sum(n) * 100
)

sum_lines |> 
  ggplot() +
  geom_point(aes(season, n, color = speaker_end, group = speaker_end)) +
  geom_line(aes(season, n, color = speaker_end, group = speaker_end)) +
  # geom_point(aes(season, sum, color = speaker_end, group = speaker_end), shape = "square") +
  scale_color_viridis_d(end = 0.9) +
  theme_light()

```

```{r}

transcripts_clean |> 
  filter(type == "dialogue") |> 
  group_by(season, episode) |> 
  count(episode) |> 
  collect() |> 
  group_by(season) |> 
  summarise(mean = mean(n)) |> 
  mutate(season = as_factor(season)) |> 
  ggplot(aes(season, mean)) +
  geom_point() +
  theme_light() +
  labs(
    x = "Season",
    y = "Mean Number of Dialogue Lines"
  )

```

```{r}
#| label: split-multispeaker-lines

transcripts_clean |> 
  select(season, episode, line, type, speaker, transcript) |> 
  filter(str_detect(speaker, "\\sAND\\s|,|/")) |> 
  collect()

multispeaker_lines <- transcripts_clean |> 
  select(season, episode, line, type, speaker, transcript) |> 
  filter(type == "dialogue") |> 
  collect() |> 
  mutate(
    speaker = speaker |> 
      str_replace("^V/O", "VOICEOVER"),
    type = type |> 
      replace_when(
        str_detect(speaker, "\\s(AND)\\b|&\\s") ~ "dialogue_multi",
        str_detect(speaker, "[A-Z]+,\\s[A-Z]+") ~ "dialogue_multi",
        str_detect(speaker, "(BRADFORD/JAKE)|(CHEN/SAVA)") ~ "dialogue_UC",
        str_detect(speaker, str_flatten(aliases$pattern, "|")) 
          ~ "dialogue_alias",
        str_detect(speaker, "[A-Z]+/[A-Z]+") ~ "dialogue_multi"
      )
  ) |> 
  mutate(speaker = speaker |> 
           replace_values(from = aliases$pattern, to = aliases$name)) |> 
  filter(type == "dialogue_multi")
  
multispeaker_lines |> 
  select(speaker, transcript) |> 
  separate_wider_delim(
    speaker,
    delim = regex(",\\s|/|&\\s|(?<![A-Z])AND\\s|(?<=\\s)AND\\s|,\\sAND"),
    names = c("a", "b", "c", "d", "e"),
    too_few = "align_start",
    too_many = "debug",
    cols_remove = FALSE
  ) |> 
  mutate(
    across(a:e, \(x) str_trim(x) |> replace_when(x == "" ~ NA_character_))
  ) |> 
  pivot_longer(a:e, names_to = "col", values_to = "name") |> 
  filter_out(is.na(name))

  # "(,\\s|/|(?<!\\s)AND(?=\\s)|and\\s|&\\s)"

  # separate_longer_delim(speaker, delim = regex("(,\\s|\\sand\\s|/|\\s&\\s)"))

transcripts_clean |> 
  select(season, episode, line, type, speaker, transcript) |>
  filter(transcript == "") |> 
  collect()

transcripts_clean |> 
  select(season, episode, line, type, speaker, transcript) |>
  filter(type == "scene_heading") |> 
  group_by(season, episode) |> 
  count() |> 
  collect()

transcripts_clean |> 
  select(season, episode, line, type, speaker, transcript) |> 
  collect() |> 
  peek_rows(type, "previously")

```


```{r}

# count line types by season

transcripts_clean |> 
  group_by(season) |> 
  count(type) |> 
  collect()

# count line types by episode

transcripts_clean |> 
  group_by(season, episode) |> 
  count(type) |> 
  collect()

# count line types by none

transcripts_clean |> 
  group_by(all_of("")) |> 
  count(type) |> 
  collect()

```

```{r}

# count dialogue lines per character

transcripts_clean |>
  filter(when_all(
    type == "dialogue",
    when_any(
      speaker_start %in% main_chars$first_name & 
        speaker_end %in% main_chars$last_name,
      is.na(speaker_start) & speaker_end %in% main_chars$last_name
    )
  )) |> 
  group_by(speaker_start, speaker_end) |>
  count() |>
  collect()

# by season

transcripts_clean |>
  filter(when_all(
    type == "dialogue",
    when_any(
      speaker_start %in% main_chars$first_name & 
        speaker_end %in% main_chars$last_name,
      is.na(speaker_start) & speaker_end %in% main_chars$last_name
    )
  )) |> 
  group_by(season, speaker_start, speaker_end) |>
  count() |>
  collect()

# by episode

transcripts_clean |>
  filter(when_all(
    type == "dialogue",
    when_any(
      speaker_start %in% main_chars$first_name & 
        speaker_end %in% main_chars$last_name,
      is.na(speaker_start) & speaker_end %in% main_chars$last_name
    )
  )) |> 
  group_by(season, episode, speaker_start, speaker_end) |> 
  count() |> 
  collect()

```

```{r}
#| label: clean-lyrics

# transcripts_clean |> 
#   select(type, speaker, transcript) |> 
#   filter(transcript == "") |> 
#   collect()

# dim(transcripts_clean)

transcripts_clean |> 
  select(season, episode, type, speaker, transcript) |> 
  collect() |> 
  peek_rows(transcript, "♪", fmt = "g")

transcripts_clean |> 
  select(type, speaker, speaker_note, transcript) |> 
  filter(str_detect(transcript, "\u266a")) |> 
  collect()

transcripts_clean |> 
  select(type, speaker, speaker_note, transcript) |> 
  filter(str_detect(transcript, "\u266a")) |> 
  collect() |> 
  mutate(
    transcript = transcript |> 
      str_replace_all("\u266a\\s(/\\s)?\u266a", "\u266a") |> 
      str_remove("\u266a(\\s\\.{3})?$") |> 
      str_trim()
  ) |> 
  separate_longer_delim(transcript, delim = regex("(?=♪)")) |> 
  mutate(
    type = type |> replace_when(str_detect(transcript, "\u266a") ~ "lyrics")
  )

transcripts_clean |> 
  select(season, episode, type, speaker, speaker_note, transcript) |> 
  filter(str_detect(transcript, "\u266a")) |> 
  collect() |> 
  mutate(
    transcript = transcript |> 
      str_replace_all("\u266a\\s(/\\s)?\u266a", "\u266a") |> 
      str_remove("\u266a(\\s\\.{3})?$") |> 
      str_trim()
  ) |> 
  separate_longer_delim(transcript, delim = regex("\\s(?=♪)")) |>
  mutate(
    type = type |> replace_when(str_detect(transcript, "\u266a") ~ "lyrics"),
    transcript = transcript |> str_remove("\u266a\\s")
  )

```

```{r}
transcripts_clean |> 
  select(speaker, transcript) |> 
  filter(speaker == "KAI", str_detect(transcript, "\u266a")) |> 
  collect() |> 
  mutate(id = row_number()) |> 
  rows_insert(tibble(id = 10, speaker = "KAI", transcript = "[ Gunshots ]"))
  
transcripts_clean |> 
  select(season, line, speaker, transcript) |> 
  filter(season == 4, speaker == "KAI") |> 
  collect()

transcripts_clean |> 
  select(season, line, speaker, transcript) |> 
  filter(season == 4, speaker == "KAI") |> 
  collect() |> 
  mutate(transcript = transcript |> str_replace(
      coll("♪ La gente paga [ Gunshots ]"), "♪ La gente paga"
    )) |>
  rows_append(filter(transcripts_clean |> 
  select(season, line, speaker, transcript) |> 
  filter(season == 4, speaker == "KAI") |> 
  collect(), speaker == "KAI", str_detect(transcript, "gente"))) |>
    mutate(transcript = transcript |> str_replace(
      coll("♪ La gente paga [ Gunshots ]"), "[Gunshots]"
    ))

transcripts_clean |> 
  select(season, line, speaker, transcript) |> 
  filter(season == 4, speaker == "KAI") |> 
  collect() |> 
  separate_longer_delim(transcript, regex("\\s(?=\\[)"))

transcripts_clean |> 
  select(season, line, speaker, transcript) |> 
  filter(speaker == "KAI", str_detect(transcript, "gente")) |> 
  collect() |> 
  separate_longer_delim(transcript, regex("\\s(?=\\[)"))

transcripts_clean |> 
  select(season, line, speaker, transcript) |> 
  filter(speaker == "KAI", str_detect(transcript, "gente")) |> 
  collect() |> 
  add_row(
    transcripts_clean |> 
  select(season, line, speaker, transcript) |> 
  filter(speaker == "KAI", str_detect(transcript, "gente")) |> 
  collect() |> 
  separate_longer_delim(transcript, regex("\\s(?=\\[)"))
  )

transcripts_clean |> 
  select(speaker, transcript) |> 
  collect() |> 
  mutate(row_num = row_number()) |> 
  filter(speaker == "KAI", str_detect(transcript, "gente"))
```

<!-- ♪ -->

```{r}
transcripts_lines |> 
  select(season, episode, transcript) |> 
  collect() |> 
  mutate(
    transcript = transcript |> 
        # Move <i> from middle to beginning of word
        str_replace_all("(\\w+)<i>", "<i>\\1") |> 
        # remove ":\\s" separating name and dialogue; names from lower to upper
        str_replace("(^[A-Z0-9][A-Z0-9\\s\\.\\-\\'#&,/]+):\\s", "\\1") |> 
        str_replace(
          "^([A-Z][a-zA-Z0-9\\s#/,]+):\\s",
          \(x) str_remove(str_to_upper(x), ":\\s")
        ) |> 
        # un-italicize lyrics
        str_remove("^<i>(?=\u266a)") |> 
        str_remove("(?<=\u266a)</i>"),
      type = case_when(
        str_detect(transcript, "Previously") &
          str_detect(transcript, "(?i)Rookie")           ~ "previously",
        # str_detect(transcript, "\u266a")                 ~ "lyrics",
        transcript %in% captions                         ~ "caption",
        str_detect(transcript, "(INT|EXT)(\\.|,)")       ~ "scene_heading",
        str_detect(transcript, "^(INT|EXT)(\\.|,|\\s)")  ~ "scene_heading",
        str_detect(transcript, "PATROL\\sCAR")           ~ "scene_heading",
        transcript %in% other_scene_headings             ~ "scene_heading",
        str_detect(transcript, "MID-WILSHIRE\\sSTATION") ~ "scene_heading",
        str_detect(transcript, "^<i>")                   ~ "italics",
        transcript %in% other_type_patterns              ~ "other"
      ),
    is_lyrics = case_when(str_detect(transcript, "\u266a") ~ TRUE),
    transcript = transcript |> str_remove("^\u266a\\s") |> str_remove("\\s\u266a$"),
      is_speaker = if_else(
        is.na(type),
        str_detect(transcript, speaker_name_patterns) &
          !str_detect(transcript, not_speaker_patterns),
        FALSE
      ),
      is_break = is_speaker | !is.na(type),
      group_id = cumsum(is_break),
      .by = c(season, episode)
    ) |>
    # relocate(c(line, type), .after = episode) |>  
  peek_rows(transcript, "Stars shining", fmt = "g")

```

```{r}
transcripts_clean |> 
  select(season, episode, type, speaker, transcript) |> 
  filter(str_detect(transcript, "\\s[A-Z]+\\s[\\(|\\[]")) |> 
  collect()

transcripts_clean |> 
  select(season, episode, type, speaker, transcript) |> 
  filter(str_detect(speaker, "ACTOR")) |> 
  collect()

transcripts_lines |>
  select(season, episode, transcript) |>
  filter(str_detect(transcript, "[A-Z]+\\s\\([^)]+\\)")) |>
  arrange(season, episode) |> 
  filter(!str_detect(transcript, "INT|EXT|(PATROL)")) |> 
  collect() |> 
  anti_join(
    transcripts_lines |>
      select(season, episode, transcript) |>
      filter(str_detect(transcript, "[A-Z]+\\s\\([^)]+\\)")) |>
      arrange(season, episode) |> 
      filter(!str_detect(transcript, "INT|EXT|(PATROL)")) |>
      filter(str_detect(transcript, "^[A-Z0-9][A-Z0-9\\s\\.\\-\\'#&,/]+\\s\\(.+\\)$")) |>
      collect(),
    by = join_by(transcript)
  )

transcripts_lines |>
  select(season, episode, transcript) |>
  filter(str_detect(transcript, "[A-Z]+\\s\\([^)]+\\)")) |>
  arrange(season, episode) |> 
  collect() |> 
  anti_join(
    transcripts_lines |>
  select(season, episode, transcript) |>
  filter(str_detect(transcript, "[A-Z]+\\s\\([^)]+\\)")) |>
  arrange(season, episode) |> 
  # filter(!str_detect(transcript, "INT|EXT|(PATROL)")) |>
  filter(str_detect(transcript, "^[A-Z0-9][A-Z0-9\\s\\.\\-\\'#&,/]+\\s\\(.+\\)$")) |>
  collect()
    , by = join_by(transcript)
  )

```

```{r}
transcripts_lines |> 
  select(season, episode, transcript) |> 
  collect() |> 
  peek_rows(transcript, "Help us! He's got a gun!")

transcripts_clean |> 
  select(season, episode, type, speaker, speaker_note, transcript) |> 
  collect() |> 
  peek_rows(transcript, "Help us! He's got a gun!")

transcripts_clean |> 
  select(season, episode, type, transcript) |> 
  filter(type == "scene_heading", str_detect(transcript, "\\[")) |> 
  # select(-type) |> 
  collect() |> 
  mutate(
    transcript = transcript |> 
      str_replace("\\s(?=\\[)", "\u2757")
  ) |> 
  separate_longer_delim(transcript, regex("\u2757")) |> 
  mutate(type = type |> replace_when(str_detect(transcript, "\\[") ~ "description"))

# Watch 2x18 for "[ Gunshots, people screaming ] Help us! He's got a gun!" to see who speaks; modify transcript by adding speaker name

transcripts_html$transcript[38] |> 
    str_replace(
      coll("[ Gunshots, people screaming ]\nHelp us! He's got a gun!"),
      "[ Gunshots, people screaming ]\nWOMAN\nHelp us! He's got a gun!"
    ) |> 
  peek_match("gun!", 70)

# "[ Gunshots, people screaming ]\nWOMAN\nHelp us! He's got a gun!"

```

```{r}
transcripts_clean |> 
  select(season, episode, type, transcript) |> 
  filter(type == "scene_heading", str_detect(transcript, "\\[")) |> 
  # select(-type) |> 
  collect() |> 
  mutate(
    transcript = transcript |> 
      str_replace("\\s(?=\\[)", "\u2757")
  ) |> 
  separate_longer_delim(transcript, regex("\u2757")) |> 
  mutate(type = type |> replace_when(str_detect(transcript, "\\[") ~ "description"))
```

```{r}
transcripts_clean |> 
  select(season, episode, type, transcript) |> 
  filter(type == "scene_heading") |> 
  collect()
  
transcripts_lines |> 
  select(transcript) |> 
  collect() |> 
  peek_rows(transcript, "The mall is crowded")

transcripts_clean |> 
  select(season, episode, type, transcript) |> 
  filter(type == "scene_heading", str_detect(transcript, "[a-z]")) |> 
  collect()

transcripts_clean |>
  filter(type == "scene_heading", str_detect(transcript, "[a-z]")) |>
  collect() |>
  mutate(
    split_point = str_extract(
      transcript, "[A-Z0-9,\\.\\-']+\\s+[A-Z][a-z].{0,20}"
    )
  ) |>
  select(transcript, split_point)
```

```{r}
transcripts_clean |> 
  select(season, episode, type, speaker, speaker_note, transcript) |> 
  collect() |> 
  peek_rows(condition = transcript == "")

transcripts_clean |> 
  select(season, episode, type, speaker, transcript) |> 
  filter(transcript == "") |> 
  collect()

transcripts_clean |> 
  select(season, episode, type, speaker, transcript) |> 
  filter(str_detect(speaker, "\\d")) |> 
  collect()

transcripts_clean |> 
  select(season, episode, type, speaker, transcript) |> 
  filter(str_detect(transcript, "^OK")) |> 
  collect()

```

```{r}

transcripts_clean |> 
  select(season, episode, type, speaker, transcript) |>  
  filter(str_detect(speaker, "^[\\d-\\s,]+\\.?$")) |> 
  collect()

transcripts_lines |> 
  select(season, episode, transcript) |> 
  collect() |> 
  peek_rows(transcript, "PILOT A2")

```

```{r}
#| label: clean-dispatch-names

transcripts_clean |> 
  select(speaker, speaker_start, speaker_end) |> 
  filter(str_detect(speaker, "(911|9\\-1\\-1)|(?i)(dispatch|operator)")) |> 
  unique() |>
  collect()
  
transcripts_clean |> 
  select(season, episode, speaker, transcript) |> 
  filter(str_detect(speaker, "^OPERATOR")) |> 
  collect()

transcripts_clean |> 
  select(speaker) |> 
  filter(str_detect(speaker, "(911|9\\-1\\-1)|(?i)(dispatch|operator)")) |> 
  unique() |> 
  collect() |> 
  filter_out(str_detect(speaker, "DRONE")) |> 
  pull(speaker)

```

```{r}
#| label: clean-lyrics2

transcripts_lines |> 
  select(ep_ID, transcript) |> 
  collect() |> 
  peek_rows(transcript, "I am totally playing mind games", after = 5, fmt = "t")

transcripts_lines |> 
  select(ep_ID, transcript) |> 
  collect() |> 
  peek_rows(transcript, "\u266a", fmt = "t")

transcripts_clean |> 
  select(season, episode, type, speaker, transcript) |> 
  collect() |> 
  peek_rows(transcript, "\u266a", fmt = "g")

# transcripts_clean |> 
#   select(season, episode, type, speaker, speaker_note, transcript) |> 
#   collect() |> 
#   peek_rows(transcript, "♪", fmt = "g")

transcripts_clean |> 
  select(season, episode, type, speaker, transcript) |> 
  collect() |> 
  peek_rows(transcript, "♪", fmt = "t")

# transcripts_clean |> 
#   select(type, speaker, speaker_note, transcript) |> 
#   filter(str_detect(transcript, "\u266a")) |> 
#   collect()

transcripts_clean |> 
  select(season, episode, type, speaker, transcript) |> 
  filter(type == "lyrics") |> 
  collect()

```

```{r}
transcripts_clean |> 
  select(season, episode, type, speaker, speaker_note, transcript) |> 
  collect() |> 
  peek_rows(condition = transcript == "")

transcripts_clean |> 
  select(type, speaker, transcript) |> 
  filter(transcript == "") |>
  collect()

transcripts_lines |> 
  select(ep_ID, transcript) |> 
  collect() |> 
  peek_rows(transcript, "<i>", fmt = "t")

transcripts_clean |> 
  select(season, episode, type, speaker, speaker_note, transcript) |> 
  filter(season == 1, episode %in% c(17)) |> 
  collect() |> 
  peek_rows(transcript, "<i>", fmt = "g")

transcripts_clean |> 
  select(ep_ID, type, speaker, speaker_note, transcript) |> 
  collect() |> 
  peek_rows(transcript, "<i>", fmt = "t")

```

```{r}

transcripts_clean |> 
  select(type, speaker, transcript) |> 
  filter(str_detect(transcript, "</?i>")) |> 
  collect()

transcripts_clean |> 
  select(season, episode, type, speaker, speaker_note, transcript) |> 
  filter(season == 1, episode >= 9, str_detect(transcript, "</?i>")) |> 
  collect() |> 
  mutate(
    speaker_note = speaker_note |> str_remove("</?i>"),
    transcript = transcript |> 
      str_replace_all("\\s(?=<i>)", "\u270a") #|> 
      # str_replace_all("(?<=</i>)\\s", "\u270a")
  ) |> 
  separate_longer_delim(transcript, regex("\u270a")) |> 
  gt()

```

```{r}

transcripts_clean |> 
  select(season, episode, type, speaker, speaker_note, transcript) |> 
  filter(season == 1, episode %in% c(17)) |>
  filter(str_detect(transcript, "^(\\(|\\[)")) |> 
  collect() |> 
  mutate(
    speaker_note = speaker_note |> replace_when(
      str_detect(transcript, "^(\\(|\\[)") ~ str_extract(transcript, "^.+(\\)|\\])(?=\\s)")
    ),
    transcript = transcript |> str_remove("^.+(\\)|\\])\\s")  
  )

transcripts_clean |> 
  select(season, episode, type, speaker, speaker_note, transcript) |> 
  filter(str_detect(transcript, "^(\\(|\\[)")) |> 
  collect() |> 
  mutate(transcript = transcript |> 
           str_replace_all("(?<=[\\)|\\]])\\s", "\u270a") |> 
           str_replace_all("(?<=\\.|\\!|\\?)\\s(?=[\\(|\\[])", "\u270a")
  ) |> 
  separate_longer_delim(transcript, regex("\u270a")) |> 
  mutate(
    type = type |> replace_when(
      when_all(
        type == "dialogue",
        str_detect(transcript, "^(\\(|\\[).+(\\)|\\])$")
      ) ~ "description"
    ),
    speaker = speaker |> replace_when(
      when_all(
        type == "description",
        str_detect(transcript, "^(\\(|\\[).+(\\)|\\])$")
      ) ~ NA_character_
    )
  ) |> 
  gt()

transcripts_clean |> 
  select(season, episode, type, speaker, speaker_note, transcript) |> 
  filter(season == 1) |> 
  collect() |> 
  peek_rows(type, "description")

transcripts_clean |> 
  select(season, episode, type, speaker, speaker_note, transcript) |> 
  filter(season == 4, episode == 7) |> 
  collect() |> 
  mutate(transcript = transcript |> 
           str_replace_all("(?<=\\.|\\!|\\?|</i>|[A-Z])\\s(?=[\\(|\\[])", "\u2757") 
    ) |> 
  separate_longer_delim(transcript, regex("\u2757"))

```

```{r}

transcripts_clean |> 
  select(season, episode, type, speaker, speaker_note, transcript) |> 
  filter(season == 2, episode == 15) |> 
  collect() |> 
  mutate(
    transcript = if_else(
      type == "italics",
      transcript |> str_replace_all("(?<=</i>)\\s(?=[A-Z])", "\u270a"),
      transcript
    )
  ) |> 
  separate_longer_delim(transcript, "\u270a") |> 
  mutate(
    type = type |> replace_when(
      str_detect(transcript, "<i>", negate = TRUE) ~ "dialogue"
    ),
    # speaker = speaker |> replace_when(
    #   when_all(
    #     type == "dialogue", is.na(speaker), lag(type, 1) == "italics"
    #   ) ~ lag(speaker, 2)
    # ),
    last_dialogue_speaker = if_else(type == "dialogue", speaker, NA_character_)
  ) |> 
  fill(last_dialogue_speaker) |> 
  mutate(speaker = speaker |> replace_when(
       when_all(type == "dialogue", is.na(speaker)) ~ last_dialogue_speaker
    )) |> 
  peek_rows(transcript, "<i>\\(")

transcripts_clean |> 
  select(season, episode, type, speaker, transcript) |> 
  filter(season %in% 5:8) |>
  collect() |> 
  peek_rows(transcript, "<i>\\(")

```

```{r}

transcripts_clean |> 
  select(season, episode, type, speaker, transcript) |> 
  filter(season == 2, episode == 15) |> 
  collect() |> 
  mutate(
    transcript = if_else(
      when_all(
        str_starts(type, "dialogue"),
        str_detect(transcript, "</?i>")
      ),
      transcript |> 
        str_replace_all("\\s(?=<i>\\()", "\u2757") |>
        str_replace_all("(?<=\\)</i>)\\s", "\u2757"),
      transcript
    )
  ) |> 
  separate_longer_delim(transcript, "\u2757") |> 
  mutate(
    type = type |> replace_when(
      when_all(type == "dialogue", str_starts(transcript, "<i>")) ~ "italics"
    ),
    speaker = speaker |> replace_when(
      when_all(
        type == "dialogue", str_starts(transcript, "<i>")
      ) ~ NA_character_
    )
  ) |>
  peek_rows(transcript, "</?i>")

```

```{r}
transcripts_clean |> 
  select(season, episode, type, speaker, transcript) |> 
  filter(season == 2, episode == 15) |> 
  collect() |> 
  peek_rows(transcript, "</?i>")
  
```

```{r}
transcripts_clean |> 
  select(season, episode, type, speaker, transcript) |> 
  filter(season == 1, episode == 15) |> 
  collect() |> 
  peek_rows(transcript, "^[\\[|\\(].+[\\]|\\)]$")
```

```{r}
transcripts_clean |> 
  select(season, episode, type, speaker, transcript) |> 
  # filter(season == 1) |> 
  collect() |> 
  # peek_rows(transcript, "^\\[.+[^\\]]$")
  peek_rows(transcript, "^[^\\[].+\\]$")
```

```{r}
transcripts_clean |> 
  select(season, episode, type, speaker, transcript) |> 
  collect() |> 
  peek_rows(transcript, "^[^\\(].+\\)$")
```

```{r}
transcripts_clean |> 
  select(season, episode, type, speaker, transcript) |> 
  filter(season == 1, episode == 1) |>
  collect() |> 
  mutate(
    transcript = if_else(
      type == "italics",
      transcript |> 
        str_replace_all("</i>\\s\\[", "</i>\u2757\\[") |> 
        str_replace_all("\\]\\s\\[", "\\]\u2757\\["),
      transcript
    )
  ) |> 
  separate_longer_delim(transcript, "\u2757") |> 
  peek_rows(transcript, "GLASS SHATTERS")
```

```{r}

# () then dialogue

transcripts_clean |> 
  select(season, episode, type, speaker, transcript) |> 
  collect() |> 
  peek_rows(transcript, "^\\(.+[^\\)]$")

# [] then dialogue

transcripts_clean |> 
  select(season, episode, type, speaker, transcript) |> 
  collect() |> 
  peek_rows(transcript, "^\\[.+[^\\]]$")

# dialogue then ()

transcripts_clean |> 
  select(season, episode, type, speaker, transcript) |> 
  collect() |> 
  peek_rows(transcript, "^[^\\(].+\\)$")

# dialogue then []

transcripts_clean |> 
  select(season, episode, type, speaker, transcript) |> 
  collect() |> 
  peek_rows(transcript, "^[^\\[].+\\]$")

```

```{r}
tibble(x = c("(in <i>Cantonese</i>)", "<i>(TEST</i>)")) |>
  mutate(x = if_else(
    str_detect(x, "<i>\\("),
    str_replace_all(x, "</i>\\)", "\\)</i>"),
    x
  ))
```

```{r}

# () then dialogue

transcripts_clean |> 
  select(season, episode, type, speaker, transcript) |> 
  collect() |> 
  peek_rows(transcript, "^\\(.+[^\\)]$")

# [] then dialogue

transcripts_clean |> 
  select(season, episode, type, speaker, transcript) |> 
  collect() |> 
  peek_rows(transcript, "^\\[.+[^\\]]$")

# dialogue then ()

transcripts_clean |> 
  select(season, episode, type, speaker, transcript) |> 
  collect() |> 
  peek_rows(transcript, "^[^\\(].+\\)$")

# dialogue then []

transcripts_clean |> 
  select(season, episode, type, speaker, transcript) |> 
  collect() |> 
  peek_rows(transcript, "^[^\\[].+\\]$")

```

```{r}
transcripts_clean |> 
  select(season, episode, type, speaker, transcript) |> 
  filter(season == 8, episode == 3) |>
  collect() |> 
  mutate(
    transcript = transcript |> 
      str_replace_all("\\)(?=[A-Z]|\")", ") ")
  ) |> 
  peek_rows(transcript, "grad")

transcripts_clean |> 
  select(season, episode, type, speaker, transcript) |> 
  filter(season == 7, episode == 14) |>
  collect() |> 
  peek_rows(transcript, "BYSTANDER", fmt = "t")
```

```{r}
transcripts |> 
  pre_split_clean() |> 
  filter(season == 7, episode == 14) |> 
  transcripts_to_lines()  |> 
  select(-c(pdf, html)) |> 
  peek_rows(transcript, "Get down on your knees. Interlace", fmt = "g")

transcripts |> 
  pre_split_clean() |> 
  filter(season == 7, episode == 14) |> 
  transcripts_to_lines()  |> 
  clean_transcripts() |> 
  select(season, episode, type, speaker, transcript) |> 
  peek_rows(transcript, "Get down on your knees. Interlace", fmt = "g")

transcripts |> 
  pre_split_clean() |> 
  filter(season == 7, episode == 14) |> 
  transcripts_to_lines()  |> 
  clean_transcripts() |> 
  select(season, episode, type, speaker, transcript) |> 
  split_italics_dialogue() |> 
  peek_rows(transcript, "Get down on your knees. Interlace", fmt = "g")
```

```{r}
transcripts |> 
  pre_split_clean() |> 
  filter(season == 4, episode == 9) |> 
  transcripts_to_lines()  |> 
  select(-c(pdf, html)) |> 
  peek_rows(transcript, "dirty", fmt = "g")

transcripts |> 
  pre_split_clean() |> 
  filter(season == 4, episode == 9) |> 
  transcripts_to_lines()  |> 
  clean_transcripts() |> 
  select(season, episode, type, speaker, transcript) |> 
  peek_rows(transcript, "dirty", fmt = "g")

transcripts |> 
  pre_split_clean() |> 
  filter(season == 4, episode == 9) |> 
  transcripts_to_lines()  |> 
  clean_transcripts() |> 
  split_italics_dialogue() |> 
  select(season, episode, type, speaker, transcript) |> 
  peek_rows(transcript, "dirty", fmt = "g")

```

```{r}
transcripts_clean |> 
  select(season, episode, type, speaker, speaker_note, transcript) |> 
  filter(season == 1) |>
  collect() |> 
  peek_rows(transcript, "^[^(\\(|\\[)].+[\\]|\\)]$", fmt = "g", before = 2)
```

```{r}

check_lines <- list(
  # start_parentheses  = "^\\(.+\\).+",
  # middle_parentheses = "^.+\\(.+\\).+$",
  # end_parentheses    = "^.+\\(.+\\)$",
  # all_parentheses    = "^\\(.+\\)$",
  # start_brackets     = "^\\[.+\\].+$",
  # middle_brackets    = "^.+\\[.+\\].+$",
  # end_brackets       = "^.+\\[.+\\]$",
  # all_brackets       = "^\\[.+\\]$",
  # start_italics      = "^<i>.+</i>.+",
  # middle_italics     = "^.+<i>.+</i>.+$",
  # end_italics        = "^.+<i>.+</i>$",
  # all_italics        = "^\\<i\\>.+\\</i\\>$",
  caps_word            = "^[(LAPD)][A-Z]{2,}"
)

map(check_lines, \(x) {
  transcripts_clean |> 
    select(season, episode, type, speaker, speaker_note, transcript) |> 
    filter(season == 2, type == "dialogue") |> 
    filter(str_detect(transcript, "[^(LAPD)][A-Z]{3,}")) |> 
    collect() |> 
    pull(transcript)
})

```
```{r}

transcripts_clean |> 
  select(season, episode, type, speaker, speaker_note, transcript) |> 
  filter(tra) |> 
  collect() |> 
  mutate(transcript = str_trunc(transcript, 28, side = "right")) |> 
  distinct()

```

