---
title: "transcripts-exp3"
format: html
---

Test unnesting of tokens

```{r}
tar_load(starts_with("df"))
df_raw          <- open_dataset(df_raw)
df_clean        <- open_dataset(df_clean)
```

```{r}
dim(df_raw)
dim(df_clean)
colnames(df_raw)
colnames(df_clean)
```

```{r}
test_df <- transcripts |> 
  run_cleaning_pipe() |> 
  arrow_table()
```

```{r}

test_df |> 
  select(season:transcript) |> 
  filter(str_detect(speaker, green_circle)) |> 
  collect() |> 
  gt()

test_df |> 
  select(season:transcript) |> 
  filter(str_detect(speaker, green_circle)) |> 
  collect() |> 
  separate_longer_delim(speaker, green_circle) |> 
  gt()

```

```{r}

test_df |> 
  select(season:transcript) |> 
  filter_out(is.na(speaker)) |> 
  distinct(speaker) |> 
  collect() |> 
  mutate(n_words = str_count(speaker, "\\s") + 1)

test_df |> 
  select(season:transcript) |> 
  filter_out(is.na(speaker)) |> 
  distinct(speaker) |> 
  collect() |> 
  mutate(n_words = str_count(speaker, "\\s") + 1) |> 
  count(n_words)

test_df |> 
  select(season:transcript) |> 
  filter_out(is.na(speaker)) |> 
  distinct(speaker) |> 
  arrange(speaker) |> 
  collect() |> 
  mutate(n_words = str_count(speaker, "\\s") + 1) |> 
  filter(n_words == 1)

test_df |> 
  select(season:transcript) |> 
  filter_out(is.na(speaker)) |> 
  distinct(speaker) |> 
  arrange(speaker) |> 
  collect() |> 
  mutate(n_words = str_count(speaker, "\\s") + 1) |> 
  filter(n_words == 2)

test_df |> 
  select(season:transcript) |> 
  filter_out(is.na(speaker)) |> 
  distinct(speaker) |> 
  arrange(speaker) |> 
  collect() |> 
  mutate(n_words = str_count(speaker, "\\s") + 1) |> 
  filter(n_words == 3)

test_df |> 
  select(season:transcript) |> 
  filter_out(is.na(speaker)) |> 
  distinct(speaker) |> 
  arrange(speaker) |> 
  collect() |> 
  mutate(n_words = str_count(speaker, "\\s") + 1) |> 
  filter(n_words == 4)

```

```{r}
test_df |> 
  select(season:transcript) |> 
  filter_out(is.na(speaker)) |> 
  distinct(speaker) |> 
  arrange(speaker) |> 
  collect() |> 
  # filter(str_detect(speaker, "(DE|DEL|VAN|VON)\\s"))
  filter(str_detect(speaker, "\\b[A-Z]{3}\\s"))
```


```{r}
tibble(speaker = c(
  "JOHN NOLAN",
  "NOLAN",
  "SEAN DEL MONTE",
  "DEL MONTE",
  "SANDRA DE LA CRUZ",
  "DE LA CRUZ",
  "VAN DOREN",
  "AGENT BUTLER",
  "CAPTAIN ZOE ANDERSEN",
  "DETECTIVE NYLA HARPER",
  "DET. KEVIN WOLFE",
  "DR. GRACE SAWYER",
  "D.S. RYAN CARADINE",
  "M.E. LOWELL",
  "MR. EDWARDS",
  "MRS. CHEN",
  "3EYEZ",
  "BE-BOP",
  "J.J.",
  "ACTOR!LOPEZ",
  "MAN 1",
  "HENCHMAN #1",
  "KID FRIEND #1",
  "DEZ' BOSS",
  "MAN IN DISTANCE",
  "LONG BEACH PD OFFICER"
)) |> 
  separate_speaker_names()
  
# mutate(
#   multiword_surname = if_else(
#     when_any(
#       str_detect(speaker, "^DEL\\sMONTE"),
#       str_detect(speaker, "^DE\\sLA\\sCRUZ"),
#       str_detect(speaker, "VAN\\sDOREN")
#     ),
#     speaker |> str_replace_all("\\s", "_"),
#     NA_character_
#   ),
#   multiword_surname = if_else(
#     str_detect(speaker, coll("SEAN DEL MONTE")) | str_detect(speaker, "SANDRA DE LA CRUZ"),
#     speaker |> str_replace_all(" ", "_") |> str_replace("_", " "),
#     multiword_surname
#   )
# )

# str_replace_all(speaker, "(?<=[A-Z]\\s(?=[A-Z]+\\s#\\d)", "_")

```


```{r}
test_df |> 
  select(season:transcript) |> 
  filter_out(is.na(speaker)) |> 
  distinct(speaker) |> 
  arrange(speaker) |> 
  collect() |> 
  filter(str_detect(speaker, "(?i)(operator|dispatch)")) |> 
  clean_dispatch_names()
```

# df_raw

```{r}
df_raw |> 
  select(season:transcript) |> 
  collect() |> 
  peek_rows(transcript, condition = transcript == "")
```

```{r}
df_raw |> 
  select(season:transcript) |> 
  collect() |> 
  peek_rows(transcript, "Unlawfully attaching a propeller")

```

```{r}
df_raw |> 
  select(season:sp4) |> 
  filter(when_any(
    when_all(
      when_any(
        sp3 %in% characters$first_name,
        is.na(sp3)
      ),
      sp4 %in% characters$last_name
    ),
    sp4 %in% characters$first_name
  )) |> 
  collect() |> 
  distinct(pick(sp1:sp4)) |> 
  arrange(sp4, sp3, sp2, sp1)

df_raw |> 
  select(season:sp4) |> 
  filter(when_any(
    when_all(
      when_any(
        sp3 %in% characters$first_name,
        is.na(sp3)
      ),
      sp4 %in% characters$last_name
    ),
    sp4 %in% characters$first_name
  )) |> 
  collect() |> 
  distinct(pick(sp1:sp4)) |> 
  arrange(sp4, sp3, sp2, sp1) |> 
  gt()
```
```{r}
tibble(name = c(
  "LUCY CHEN", "CHEN",
  "JOHN NOLAN", "NOLAN", "HENRY NOLAN",
  "SEAN DEL_MONTE", "DEL_MONTE",
  "SANDRA DE_LA_CRUZ", "DE_LA_CRUZ")
) |> 
  pull(name) |> 
  str_view("^[A-Z_]+$")
```

```{r}
tribble(
  ~first_name, ~last_name,
  "LUCY",      "CHEN",
  NA,          "CHEN",
  "JOHN",      "NOLAN",
  NA,          "NOLAN",
  "HENRY",     "NOLAN",
  "SEAN",      "DEL_MONTE",
  NA,          "DEL_MONTE",
  "SANDRA",    "DE_LA_CRUZ",
  NA,          "DE_LA_CRUZ"
) |>
  unite(
    speaker,
    first_name, last_name,
    sep = " ",
    remove = FALSE,
    na.rm = TRUE
  ) |> 
  mutate(
    speaker = if_else(
      is.na(first_name) & str_detect(last_name, "^[A-Z_]+$"),
      TRUE,
      FALSE
    )
  )


#|> 
  # mutate(
    
    # first_name = first_name |> replace_when(
    #   when_all(
    #     is.na(first_name),
    #     last_name %in% pull(characters, last_name)
    #   ) ~ pull(characters, first_name)
    # )
  # )
```

# df_clean

# df comparison

```{r}

df_raw |> 
  select(season:transcript) |> 
  # filter(season == 8, episode == 15) |> 
  # filter(speaker == "INTERVIEWER") |> 
  filter(transcript == "") |> 
  collect()

df_clean |> 
  select(season:transcript) |> 
  # filter(season == 8, episode == 15) |>
  # filter(speaker == "INTERVIEWER") |> 
  filter(str_detect(transcript, "I never said")) |> 
  collect()

```

# Checking line mismatch (added alt line to `clean_other()`)

```{r}
anti_join(df_clean, df_raw, join_by(season, episode, line)) |> collect()
anti_join(df_clean, df_raw, join_by(transcript), copy = TRUE) |> collect()
```

```{r}
check_line_mismatch <- function(x, y, s, e, offset = FALSE) {
  
  if (offset == TRUE) {
    a <- x + 1
    b <- y + 1
  } else {
    a <- x
    b <- y
  }
  
  df_raw |>
    select(season, episode, line, type, speaker, transcript) |> 
    filter(season == s, episode == e, line >= x, line <= y) |>
    collect() |>
    gt() |> print()
  
  df_clean |>
    select(season, episode, line, type, speaker, transcript) |> 
    filter(season == s, episode == e, line >= a, line <= b) |>
    collect() |> 
    gt() |> print()
  
}

check_line_mismatch(376, 379, 8, 15)

```

```{r}

exp_raw0 <- transcripts |> 
  pre_clean() |> 
  clean_speaker_names() |>
  remove_translations() |> 
  add_brackets() |>
  replace_italics() |> 
  add_space() |> 
  split_transcripts() |>
  shift_italics_tags() |>
  clean_previously() |>
  clean_scene_headings() |>
  clean_captions() |>
  clean_other() |>
  pre_clean_lyrics() |>
  arrow_table()

exp_clean0 <- transcripts |> 
  pre_clean() |> 
  clean_speaker_names() |>
  remove_translations() |> 
  add_brackets() |>
  replace_italics() |> 
  add_space() |> 
  clean_proper_nouns() |>
  split_transcripts() |>
  shift_italics_tags() |>
  clean_previously() |>
  clean_scene_headings() |>
  clean_captions() |>
  clean_other() |>
  pre_clean_lyrics() |>
  arrow_table()

exp_raw <- transcripts |> 
  pre_clean() |> 
  clean_speaker_names() |>
  remove_translations() |> 
  add_brackets() |>
  replace_italics() |> 
  add_space() |> 
  split_transcripts() |>
  shift_italics_tags() |>
  clean_previously() |>
  clean_scene_headings() |>
  clean_captions() |>
  clean_other() |>
  pre_clean_lyrics() |>
  assign_speaker_names() |> 
  arrow_table()

exp_clean <- transcripts |> 
  pre_clean() |> 
  clean_speaker_names() |>
  remove_translations() |> 
  add_brackets() |>
  replace_italics() |> 
  add_space() |> 
  clean_proper_nouns() |>
  split_transcripts() |>
  shift_italics_tags() |>
  clean_previously() |>
  clean_scene_headings() |>
  clean_captions() |>
  clean_other() |>
  pre_clean_lyrics() |>
  assign_speaker_names() |> 
  arrow_table()

  # split_transcripts() |>
  # shift_italics_tags() |>
  # clean_previously() |>
  # clean_scene_headings() |>
  # clean_captions() |>
  # clean_other() |>
  # pre_clean_lyrics() |>
  # assign_speaker_names() |>
  # extract_speaker_note() |>
  # insert_sentinels() |>
  # unitalicize_descriptions() |> 
  # unify_sentinels() |> 
  # separate_at_sentinels() |> 
  # reclassify_type() |>
  # fill_speaker_info() |>
  # clean_multispeaker_names() |> 
  # unitalicize_descriptions2() |> 
  # replace_italics2()

```

```{r}
exp_raw0 |> 
  select(season, episode, type, transcript) |> 
  filter(str_detect(transcript, "Clips from")) |> 
  collect() |> 
  gt()
exp_clean0 |> 
  select(season, episode, type, transcript) |> 
  filter(str_detect(transcript, "Clips from")) |> 
  collect() |> 
  gt()
```

```{r}
exp_raw |> 
  select(season:transcript) |> 
  filter(str_detect(transcript, "Clips from")) |> 
  collect() |> 
  gt()

exp_clean |> 
  select(season:transcript) |> 
  filter(str_detect(transcript, "I never said that")) |> 
  collect() |> 
  gt()

exp_clean |> 
  select(season:transcript) |> 
  filter(str_detect(transcript, "Clips from")) |> 
  collect() |> 
  gt()
```
