---
title: "Episode ratings"
format: html
execute:
  echo: false
---

```{r}
tar_config_set(store = "../_targets")
tar_source("../R")
tar_load(episode_ratings)
```

```{r}
dark_teal   <- "#0a333f"
dark_teal2  <- "#0a333f30"
teal        <- "#2f8b9d"
teal2       <- "#2f8b9d30"
yellow      <- "#facf21"
yellow2     <- "#facf2125"
light_green <- "#b9d4bd"
code_color  <- "#7c13ba"
```

```{r}
gg_theme <- theme_light() +
  theme(
    axis.title = element_text(size = 15),
    axis.text = element_text(size = 14),
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 13)
  )
```

```{r}
episode_ratings |> 
  summarise(
    min = min(rating),
    q1 = quantile(rating, 0.25),
    median = median(rating),
    q3 = quantile(rating, 0.75),
    mean = mean(rating),
    max = max(rating)
  ) |> 
  pivot_longer(everything(), names_to = "statistic", values_to = "value")
```

```{r}
episode_ratings |> 
  group_by(rating) |> 
  count() |> 
  ggplot(aes(rating, n)) + 
  geom_col(fill = teal) +
  scale_x_continuous(breaks = seq(0, 10, 1)) +
  scale_y_continuous(expand = expansion(c(0, 0.05))) +
  labs(x = "Rating", y = "Number of Episodes") +
  theme_light() +
  gg_theme +
  coord_cartesian(xlim = c(0, 10))

episode_ratings |> 
  group_by(rating) |> 
  count() |> 
  ggplot(aes(rating, n)) + 
  geom_col(fill = teal) +
  scale_x_continuous(breaks = seq(0, 10, 0.5)) +
  scale_y_continuous(expand = expansion(c(0, 0.05)), breaks = seq(0, 20, 4)) +
  labs(x = "Rating", y = "Number of Episodes") +
  theme_light() +
  gg_theme
```

```{r}
episode_ratings |> 
  group_by(season) |> 
  count(rating) |> 
  mutate(season = season |> as_factor() %>% str_c("Season ", .)) |> 
  ggplot(aes(rating, n)) + 
  # geom_col(fill = teal) +
  geom_col(aes(fill = season)) +
  # geom_col(fill = teal, alpha = 0.3) +
  # geom_line() +
  # geom_line(aes(color = season), linewidth = 0.75) +
  scale_x_continuous(breaks = seq(0, 10, 1)) +
  scale_y_continuous(expand = expansion(c(0, 0.05))) +
  scale_fill_viridis_d(guide = guide_legend(position = "top")) +
  labs(x = "Rating", y = "Number of Episodes", fill = "Season") +
  gg_theme
```

```{r}
#| eval: FALSE
episode_ratings |> 
  group_by(season) |> 
  count(rating) |> 
  mutate(season = season |> as_factor() %>% str_c("Season ", .)) |> 
  ggplot(aes(rating, n)) + 
  geom_col(aes(fill = season), position = "dodge") +
  scale_x_continuous(breaks = seq(0, 10, 1)) +
  scale_y_continuous(expand = expansion(c(0, 0.05))) +
  scale_fill_viridis_d(guide = guide_legend(position = "top")) +
  labs(x = "Rating", y = "Number of Episodes", fill = "Season") +
  gg_theme
```

```{r}
episode_ratings |> 
  group_by(season) |> 
  count(rating) |> 
  mutate(
    season = season |> as_factor(),
    n = n |> as_factor()
  ) |>
  # mutate(season = season |> as_factor() %>% str_c("Season ", .)) |>
  ggplot(aes(season, rating, color = n, size = n)) + 
  geom_point() +
  # scale_y_continuous(expand = expansion(c(0, 0.05))) +
  # scale_fill_viridis_d(guide = guide_legend(position = "top")) +
  # labs(x = "Rating", y = "Number of Episodes", fill = "Season") +
  scale_color_viridis_d(direction = -1) +
  labs(x = "Season", y = "Rating", color = "Number of Episodes", size = "Number of Episodes") +
  gg_theme
```

```{r}
episode_ratings |> 
  group_by(season) |> 
  count(rating) |> 
  mutate(
    season = season |> as_factor(),
    # n = n |> as_factor()
  ) |>
  # mutate(season = season |> as_factor() %>% str_c("Season ", .)) |>
  ggplot(aes(season, rating, fill = season)) + 
  geom_violin() +
  # scale_y_continuous(expand = expansion(c(0, 0.05))) +
  # scale_fill_viridis_d(guide = guide_legend(position = "top")) +
  # labs(x = "Rating", y = "Number of Episodes", fill = "Season") +
  scale_fill_viridis_d(guide = NULL) +
  labs(x = "Season", y = "Rating") +
  gg_theme
```

```{r}
strip_labels <- setNames(
  str_c("Season ", 1:8),
  as.character(1:8)
)

episode_ratings |> 
  group_by(season) |> 
  count(rating) |> 
  mutate(season = season |> as_factor()) |> 
  ggplot(aes(rating, n)) + 
  geom_col(fill = teal) + 
  facet_wrap(
    ~ season,
    labeller = as_labeller(strip_labels),
    axes = "all_x"
  ) +
  scale_x_continuous(breaks = seq(0, 10, 1)) +
  scale_y_continuous(expand = expansion(c(0, 0.05)), minor_breaks = NULL) +
  labs(x = "Rating", y = "Number of Episodes") +
  gg_theme +
  theme(
    strip.background = element_rect(fill = yellow2),
    strip.text = element_text(color = dark_teal)
  )
```


```{r}
#| eval: false
episode_ratings |> 
  # group_by(season) |> 
  # count(rating) |> 
  mutate(season = season |> as_factor() %>% str_c("Season ", .)) |> 
  # ggplot(aes(rating, n)) + 
  ggplot(aes(rating)) +
  geom_dotplot(
    aes(color = season, fill = season),
    binwidth = 0.1,
    stackgroups = TRUE
  ) +
  # geom_line(aes(color = season)) +
  # geom_point(aes(color = season)) +
  scale_x_continuous(breaks = seq(0, 10, 0.5)) +
  scale_y_continuous(expand = expansion(c(0, 0.05))) +
  # scale_color_viridis_d(guide = guide_legend(position = "top")) +
  scale_color_viridis_d(guide = guide_legend(position = "top")) +
  scale_fill_viridis_d(guide = guide_legend(position = "top")) +
  labs(x = "Rating", y = "Number of Episodes", color = "Season", fill = "Season") +
  gg_theme  
  # coord_cartesian(ylim = c(0, 5))
```


```{r}
#| eval: false
{episode_ratings |> 
  group_by(season) |> 
  count(rating) |> 
  # mutate(season = season |> as_factor() %>% str_c("Season ", .)) |> 
  ggplot(aes(rating, n, frame = season)) + 
  geom_bar(fill = teal, stat = "identity") +
  scale_y_continuous(expand = expansion(c(0, 0.05)), minor_breaks = NULL) +
  labs(x = "Rating", y = "Number of Episodes") +
  gg_theme} %>%
  ggplotly()
```


```{r}
episode_ratings |> 
  group_by(season) |> 
  summarise(
    min = min(rating),
    q1 = quantile(rating, 0.25),
    median = median(rating),
    q3 = quantile(rating, 0.75),
    mean = mean(rating),
    max = max(rating)
  )
```

```{r}
episode_ratings |> 
  group_by(season) |> 
  summarise(
    min = min(rating),
    q1 = quantile(rating, 0.25),
    median = median(rating),
    q3 = quantile(rating, 0.75),
    mean = mean(rating),
    max = max(rating)
  ) |> 
  pivot_longer(2:last_col(), names_to = "stat", values_to = "value") |> 
  ggplot() +
  # geom_line(aes(season, value, color = stat)) +
  geom_line(
    aes(
      season, value,
      color = fct_reorder2(stat, season, value),
      linetype = fct_reorder2(stat, season, value)
    ),
    linewidth = 0.75
  ) +
  scale_x_continuous(breaks = 1:8, minor_breaks = NULL) +
  scale_y_continuous(expand = expansion(c(0, 0))) +
  scale_color_viridis_d(end = 0.85, labels = \(x) x |> str_to_title()) +
  scale_linetype_manual(
    values = c(
      "max" = "solid", "q3" = "dotdash", "median" = "dashed",
      "mean" = "dotted", "q1" = "twodash", "min" = "longdash"
    ),
    labels = \(x) x |> str_to_title()
  ) +
  labs(x = "Season", y = "Rating", color = "Statistic", linetype = "Statistic") +
  theme_light() +
  coord_cartesian(ylim = c(0, 10))
```
